<a href="https://colab.research.google.com/github/jonathanluo23/NBA-allstar-all-nba-Prediction/blob/main/allstar_data_collection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#imports

In [ ]:
import requests
import pandas as pd

In [ ]:
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 100)
pd.set_option('display.width', 100)

#All Star Trad

In [ ]:
season_id = '2021-22'
per_mode = 'PerGame'

In [ ]:
player_info_url = 'https://stats.nba.com/stats/leaguedashplayerstats?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&GameSegment=&Height=&LastNGames=0&LeagueID=00&Location=&MeasureType=Base&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode='+per_mode+'&Period=0&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season='+season_id+'&SeasonSegment=Pre+All-Star&SeasonType=Regular+Season&ShotClockRange=&StarterBench=&TeamID=0&TwoWay=0&VsConference=&VsDivision=&Weight='

In [ ]:
headers  = {
    'Connection': 'keep-alive',
    'Accept': 'application/json, text/plain, */*',
    'x-nba-stats-token': 'true',
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36',
    'x-nba-stats-origin': 'stats',
    'Sec-Fetch-Site': 'same-origin',
    'Sec-Fetch-Mode': 'cors',
    'Referer': 'https://stats.nba.com/',
    'Accept-Encoding': 'gzip, deflate, br',
    'Accept-Language': 'en-US,en;q=0.9',
}

In [ ]:
response = requests.get(url=player_info_url, headers=headers).json()

In [ ]:
player_info = response['resultSets'][0]['rowSet']

In [ ]:
columns_list = ["PLAYER_ID"
,"PLAYER_NAME"
,"NICKNAME"
,"TEAM_ID"
,"TEAM_ABBREVIATION"
,"AGE"
,"GP"
, "W"
, "L"
,"W_PCT"
,"MIN"
,"FGM"
,"FGA"
,"FG_PCT"
,"FG3M"
, "FG3A"
,"FG3_PCT"
, "FTM"
, "FTA"
, "FT_PCT"
, "OREB"
, "DREB"
,"REB"
, "AST"
, "TOV"
, "STL"
, "BLK"
,"BLKA"
, "PF"
, "PFD"
,"PTS"
,"PLUS_MINUS"
, "NBA_FANTASY_PTS"
, "DD2"
,"TD3"
, "WNBA_FANTASY_PTS"
, "GP_RANK"
,"W_RANK"
,"L_RANK"
, "W_PCT_RANK"
, "MIN_RANK"
, "FGM_RANK"
, "FGA_RANK"
, "FG_PCT_RANK"
, "FG3M_RANK"
, "FG3A_RANK"
, "FG3_PCT_RANK"
, "FTM_RANK"
, "FTA_RANK"
, "FT_PCT_RANK"
, "OREB_RANK"
, "DREB_RANK"
, "REB_RANK"
,"AST_RANK"
, "TOV_RANK"
,"STL_RANK"
, "BLK_RANK"
,"BLKA_RANK"
,"PF_RANK"
,"PFD_RANK"
,"PTS_RANK"
,"PLUS_MINUS_RANK"
, "NBA_FANTASY_PTS_RANK"
,"DD2_RANK"
,"TD3_RANK"
,"WNBA_FANTASY_PTS_RANK"
,"CFID"
,"CFPARAMS"]

In [ ]:
trad_22 = pd.DataFrame(player_info, columns=columns_list)

In [ ]:
trad_22

,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP,W,L,W_PCT,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,TOV,STL,BLK,BLKA,PF,PFD,PTS,PLUS_MINUS,NBA_FANTASY_PTS,DD2,TD3,WNBA_FANTASY_PTS,GP_RANK,W_RANK,L_RANK,W_PCT_RANK,MIN_RANK,FGM_RANK,FGA_RANK,FG_PCT_RANK,FG3M_RANK,FG3A_RANK,FG3_PCT_RANK,FTM_RANK,FTA_RANK,FT_PCT_RANK,OREB_RANK,DREB_RANK,REB_RANK,AST_RANK,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,WNBA_FANTASY_PTS_RANK,CFID,CFPARAMS
0,203932,Aaron Gordon,Aaron,1610612743,DEN,26.0,53,31,22,0.585,31.8,5.6,10.9,0.516,1.2,3.5,0.333,2.1,2.8,0.735,1.7,4.1,5.8,2.6,1.8,0.7,0.5,0.7,1.9,2.6,14.5,4.7,27.3,4,0,26.5,65,51,160,206,77,87,111,108,174,181,255,95,89,321,70,102,79,126,84,217,129,79,219,91,93,32,101,87,34,107,5,"203932,1610612743"
1,1630565,Aaron Henry,Aaron,1610612755,PHI,22.0,6,6,0,1.000,2.8,0.2,0.8,0.200,0.0,0.2,0.000,0.0,0.0,0.000,0.0,0.2,0.2,0.0,0.3,0.0,0.3,0.3,0.3,0.0,0.3,-3.3,1.2,0,0,1.2,492,434,568,1,569,553,565,552,487,517,487,520,526,520,538,566,569,545,471,522,247,278,542,541,560,488,577,221,34,576,5,"1630565,1610612755"
2,1628988,Aaron Holiday,Aaron,1610612756,PHX,25.0,44,21,23,0.477,16.0,2.5,5.2,0.480,0.6,1.7,0.370,0.6,0.8,0.800,0.2,1.4,1.7,2.0,1.0,0.6,0.2,0.2,1.5,1.0,6.2,-1.6,12.5,0,0,12.0,204,210,140,331,331,299,298,180,309,344,162,347,369,204,490,404,448,191,233,274,350,379,320,309,308,389,343,221,34,339,5,"1628988,1610612756"
3,1630174,Aaron Nesmith,Aaron,1610612738,BOS,22.0,41,24,17,0.585,10.8,1.3,3.5,0.378,0.5,2.2,0.236,0.4,0.5,0.842,0.3,1.4,1.7,0.3,0.6,0.3,0.1,0.0,1.3,0.5,3.5,0.4,6.6,0,0,6.9,246,154,259,203,431,425,410,453,339,284,430,434,458,135,464,410,439,508,370,442,454,501,374,439,428,230,466,221,34,453,5,"1630174,1610612738"
4,1630598,Aaron Wiggins,Aaron,1610612760,OKC,23.0,34,9,25,0.265,22.4,2.6,5.7,0.464,0.8,2.6,0.307,1.1,1.5,0.706,0.9,2.5,3.4,1.1,0.8,0.7,0.2,0.3,2.0,1.1,7.1,-2.6,14.9,0,0,14.3,311,400,115,503,218,272,271,211,264,244,340,243,229,357,201,268,250,307,294,206,326,297,191,278,269,456,288,221,34,284,5,"1630598,1610612760"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
587,1628380,Zach Collins,Zach,1610612759,SAS,24.0,5,3,2,0.600,16.4,2.4,5.4,0.444,0.6,1.4,0.429,0.4,0.8,0.500,1.6,3.6,5.2,2.2,1.6,0.8,0.4,0.6,2.2,0.6,5.8,-0.6,17.3,0,0,16.2,502,477,505,182,323,306,285,279,313,365,44,423,365,479,76,134,107,157,106,169,197,109,141,426,325,310,238,221,34,244,5,"1628380,1610612759"
588,203897,Zach LaVine,Zach,1610612741,CHI,27.0,47,31,16,0.660,34.6,8.7,18.1,0.482,2.9,7.2,0.399,4.2,4.9,0.869,0.3,4.6,4.9,4.5,2.7,0.6,0.4,0.9,1.7,3.7,24.6,2.1,37.4,0,0,38.8,160,51,293,112,32,16,21,174,21,31,93,25,32,82,473,73,123,54,38,249,217,43,254,40,15,115,38,221,34,29,5,"203897,1610612741"
589,1630192,Zeke Nnaji,Zeke,1610612743,DEN,21.0,39,23,16,0.590,16.7,2.4,4.5,0.540,0.9,1.9,0.487,1.0,1.6,0.613,1.4,2.3,3.7,0.4,0.5,0.3,0.3,0.5,1.9,1.3,6.8,-1.0,13.2,0,0,13.1,274,174,293,194,314,303,340,80,221,314,30,269,215,442,99,302,220,485,395,426,247,191,195,251,280,333,323,221,34,318,5,"1630192,1610612743"
590,1630533,Ziaire Williams,Ziaire,1610612763,MEM,20.0,40,26,14,0.650,21.5,2.9,6.5,0.441,1.1,3.7,0.284,0.5,0.6,0.760,0.3,1.5,1.8,0.9,0.6,0.6,0.2,0.3,2.0,0.7,7.3,0.8,12.3,0,0,12.4,263,124,330,124,229,244,227,289,194,165,382,396,421,259,475,388,426,373,375,282,377,336,190,386,263,193,347,221,34,327,5,"1630533,1610612763"
591,1629597,Zylan Cheatham,Zylan,1610612762,UTA,26.0,1,0,1,0.000,5.2,0.0,3.0,0.000,0.0,2.0,0.000,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-13.0,0.0,0,0,0.0,570,561,533,561,531,560,437,560,487,301,487,520,526,520,538,567,570,545,543,522,496,510,567,541,564,590,583,221,34,583,5,"1629597,1610612762"

In [ ]:
real_trad_22 = trad_22[["PLAYER_ID","PLAYER_NAME","NICKNAME"]]

In [ ]:
real_trad_22 = trad_22[["PLAYER_ID","PLAYER_NAME","NICKNAME","TEAM_ID","TEAM_ABBREVIATION","AGE","GP","W","L","W_PCT","MIN","FGM","FGA","FG_PCT","FG3M","FG3A","FG3_PCT","FTM","FTA","FT_PCT","OREB","DREB","REB","AST","TOV","STL","BLK","PF","PTS","PLUS_MINUS"]]

In [ ]:
real_trad_22

,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP,W,L,W_PCT,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,TOV,STL,BLK,PF,PTS,PLUS_MINUS
0,203932,Aaron Gordon,Aaron,1610612743,DEN,26.0,53,31,22,0.585,31.8,5.6,10.9,0.516,1.2,3.5,0.333,2.1,2.8,0.735,1.7,4.1,5.8,2.6,1.8,0.7,0.5,1.9,14.5,4.7
1,1630565,Aaron Henry,Aaron,1610612755,PHI,22.0,6,6,0,1.000,2.8,0.2,0.8,0.200,0.0,0.2,0.000,0.0,0.0,0.000,0.0,0.2,0.2,0.0,0.3,0.0,0.3,0.3,0.3,-3.3
2,1628988,Aaron Holiday,Aaron,1610612756,PHX,25.0,44,21,23,0.477,16.0,2.5,5.2,0.480,0.6,1.7,0.370,0.6,0.8,0.800,0.2,1.4,1.7,2.0,1.0,0.6,0.2,1.5,6.2,-1.6
3,1630174,Aaron Nesmith,Aaron,1610612738,BOS,22.0,41,24,17,0.585,10.8,1.3,3.5,0.378,0.5,2.2,0.236,0.4,0.5,0.842,0.3,1.4,1.7,0.3,0.6,0.3,0.1,1.3,3.5,0.4
4,1630598,Aaron Wiggins,Aaron,1610612760,OKC,23.0,34,9,25,0.265,22.4,2.6,5.7,0.464,0.8,2.6,0.307,1.1,1.5,0.706,0.9,2.5,3.4,1.1,0.8,0.7,0.2,2.0,7.1,-2.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
587,1628380,Zach Collins,Zach,1610612759,SAS,24.0,5,3,2,0.600,16.4,2.4,5.4,0.444,0.6,1.4,0.429,0.4,0.8,0.500,1.6,3.6,5.2,2.2,1.6,0.8,0.4,2.2,5.8,-0.6
588,203897,Zach LaVine,Zach,1610612741,CHI,27.0,47,31,16,0.660,34.6,8.7,18.1,0.482,2.9,7.2,0.399,4.2,4.9,0.869,0.3,4.6,4.9,4.5,2.7,0.6,0.4,1.7,24.6,2.1
589,1630192,Zeke Nnaji,Zeke,1610612743,DEN,21.0,39,23,16,0.590,16.7,2.4,4.5,0.540,0.9,1.9,0.487,1.0,1.6,0.613,1.4,2.3,3.7,0.4,0.5,0.3,0.3,1.9,6.8,-1.0
590,1630533,Ziaire Williams,Ziaire,1610612763,MEM,20.0,40,26,14,0.650,21.5,2.9,6.5,0.441,1.1,3.7,0.284,0.5,0.6,0.760,0.3,1.5,1.8,0.9,0.6,0.6,0.2,2.0,7.3,0.8
591,1629597,Zylan Cheatham,Zylan,1610612762,UTA,26.0,1,0,1,0.000,5.2,0.0,3.0,0.000,0.0,2.0,0.000,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-13.0

#advanced

In [ ]:
player_info_url_adv = 'https://stats.nba.com/stats/leaguedashplayerstats?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&GameSegment=&Height=&LastNGames=0&LeagueID=00&Location=&MeasureType=Advanced&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode='+per_mode+'&Period=0&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season='+season_id+'&SeasonSegment=Pre+All-Star&SeasonType=Regular+Season&ShotClockRange=&StarterBench=&TeamID=0&TwoWay=0&VsConference=&VsDivision=&Weight='

In [ ]:
response_adv = requests.get(url=player_info_url_adv, headers=headers).json()

In [ ]:
player_info_adv = response_adv['resultSets'][0]['rowSet']

In [ ]:
columns_list_adv = ["PLAYER_ID",
"PLAYER_NAME",
"NICKNAME",
"TEAM_ID",
"TEAM_ABBREVIATION",
"AGE",
"GP",
"W",
"L",
"W_PCT",
"MIN",
"E_OFF_RATING",
"OFF_RATING",
"sp_work_OFF_RATING",
"E_DEF_RATING",
"DEF_RATING",
"sp_work_DEF_RATING",
"E_NET_RATING",
"NET_RATING",
"sp_work_NET_RATING",
"AST_PCT",
"AST_TO",
"AST_RATIO",
"OREB_PCT",
"DREB_PCT",
"REB_PCT",
"TM_TOV_PCT",
"E_TOV_PCT",
"EFG_PCT",
"TS_PCT",
"USG_PCT",
"E_USG_PCT",
"E_PACE",
"PACE",
"PACE_PER40",
"sp_work_PACE",
"PIE",
"POSS",
"FGM",
"FGA",
"FGM_PG",
"FGA_PG",
"FG_PCT",
"GP_RANK",
"W_RANK",
"L_RANK",
"W_PCT_RANK",
 "MIN_RANK",
 "E_OFF_RATING_RANK",
"OFF_RATING_RANK",
"sp_work_OFF_RATING_RANK",
"E_DEF_RATING_RANK",
"DEF_RATING_RANK",
"sp_work_DEF_RATING_RANK",
"E_NET_RATING_RANK",
"NET_RATING_RANK",
"sp_work_NET_RATING_RANK",
 "AST_PCT_RANK",
 "AST_TO_RANK",
"AST_RATIO_RANK",
"OREB_PCT_RANK",
 "DREB_PCT_RANK",
 "REB_PCT_RANK" ,
 "TM_TOV_PCT_RANK",
 "E_TOV_PCT_RANK",
 "EFG_PCT_RANK",
"TS_PCT_RANK",
 "USG_PCT_RANK",
"E_USG_PCT_RANK",
"E_PACE_RANK",
 "PACE_RANK",
 "sp_work_PACE_RANK",
"PIE_RANK",
"FGM_RANK",
"FGA_RANK",
"FGM_PG_RANK",
"FGA_PG_RANK",
"FG_PCT_RANK",
"CFID",
"CFPARAMS"]

In [ ]:
trad_2_adv = pd.DataFrame(player_info_adv, columns=columns_list_adv)

In [ ]:
real_trad_2_adv = trad_2_adv[['PLAYER_ID','GP', 'PLAYER_NAME','W_PCT','OFF_RATING','DEF_RATING','NET_RATING','AST_PCT','AST_TO','TM_TOV_PCT',"TS_PCT","OREB_PCT","DREB_PCT","REB_PCT",'EFG_PCT',"PIE","USG_PCT","TS_PCT","PACE","POSS"]]

In [ ]:
real_trad_2_adv

,PLAYER_ID,GP,PLAYER_NAME,W_PCT,OFF_RATING,DEF_RATING,NET_RATING,AST_PCT,AST_TO,TM_TOV_PCT,TS_PCT,OREB_PCT,DREB_PCT,REB_PCT,EFG_PCT,PIE,USG_PCT,TS_PCT,PACE,POSS
0,203932,53,Aaron Gordon,0.585,116.5,109.4,7.0,0.114,1.48,10.8,0.598,0.057,0.124,0.093,0.570,0.097,0.191,0.598,98.10,3444
1,1630565,6,Aaron Henry,1.000,71.1,127.0,-56.0,0.000,0.00,28.6,0.200,0.000,0.048,0.024,0.200,-0.079,0.149,0.200,105.99,38
2,1628988,44,Aaron Holiday,0.477,103.5,108.3,-4.9,0.192,2.00,11.6,0.563,0.014,0.086,0.051,0.540,0.084,0.177,0.563,98.45,1440
3,1630174,41,Aaron Nesmith,0.585,104.4,102.3,2.2,0.045,0.54,12.9,0.479,0.026,0.119,0.074,0.451,0.042,0.166,0.479,100.46,925
4,1630598,34,Aaron Wiggins,0.265,104.0,108.1,-4.2,0.073,1.41,9.6,0.561,0.036,0.103,0.070,0.534,0.063,0.134,0.561,100.75,1591
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
587,1628380,5,Zach Collins,0.600,103.4,103.9,-0.5,0.183,1.38,16.7,0.504,0.090,0.200,0.145,0.500,0.093,0.186,0.504,104.46,177
588,203897,47,Zach LaVine,0.660,113.2,110.7,2.5,0.206,1.63,10.1,0.606,0.008,0.128,0.070,0.561,0.131,0.287,0.606,99.85,3386
589,1630192,39,Zeke Nnaji,0.590,108.1,110.8,-2.7,0.035,0.71,8.7,0.652,0.081,0.146,0.112,0.645,0.083,0.148,0.652,98.94,1341
590,1630533,40,Ziaire Williams,0.650,111.6,110.0,1.6,0.053,1.52,7.0,0.535,0.011,0.064,0.037,0.521,0.044,0.138,0.535,101.88,1829
591,1629597,1,Zylan Cheatham,0.000,18.2,125.0,-106.8,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.000,-0.167,0.250,0.000,106.50,11

In [ ]:
all_star_data_2022 = pd.merge(real_trad_2_adv, real_trad_22, how='inner', on = 'PLAYER_ID')

In [ ]:
all_star_data_2022

,PLAYER_ID,GP_x,PLAYER_NAME_x,W_PCT_x,OFF_RATING,DEF_RATING,NET_RATING,AST_PCT,AST_TO,TM_TOV_PCT,TS_PCT,OREB_PCT,DREB_PCT,REB_PCT,EFG_PCT,PIE,USG_PCT,TS_PCT,PACE,POSS,PLAYER_NAME_y,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP_y,W,L,W_PCT_y,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,TOV,STL,BLK,PF,PTS,PLUS_MINUS
0,203932,53,Aaron Gordon,0.585,116.5,109.4,7.0,0.114,1.48,10.8,0.598,0.057,0.124,0.093,0.570,0.097,0.191,0.598,98.10,3444,Aaron Gordon,Aaron,1610612743,DEN,26.0,53,31,22,0.585,31.8,5.6,10.9,0.516,1.2,3.5,0.333,2.1,2.8,0.735,1.7,4.1,5.8,2.6,1.8,0.7,0.5,1.9,14.5,4.7
1,1630565,6,Aaron Henry,1.000,71.1,127.0,-56.0,0.000,0.00,28.6,0.200,0.000,0.048,0.024,0.200,-0.079,0.149,0.200,105.99,38,Aaron Henry,Aaron,1610612755,PHI,22.0,6,6,0,1.000,2.8,0.2,0.8,0.200,0.0,0.2,0.000,0.0,0.0,0.000,0.0,0.2,0.2,0.0,0.3,0.0,0.3,0.3,0.3,-3.3
2,1628988,44,Aaron Holiday,0.477,103.5,108.3,-4.9,0.192,2.00,11.6,0.563,0.014,0.086,0.051,0.540,0.084,0.177,0.563,98.45,1440,Aaron Holiday,Aaron,1610612756,PHX,25.0,44,21,23,0.477,16.0,2.5,5.2,0.480,0.6,1.7,0.370,0.6,0.8,0.800,0.2,1.4,1.7,2.0,1.0,0.6,0.2,1.5,6.2,-1.6
3,1630174,41,Aaron Nesmith,0.585,104.4,102.3,2.2,0.045,0.54,12.9,0.479,0.026,0.119,0.074,0.451,0.042,0.166,0.479,100.46,925,Aaron Nesmith,Aaron,1610612738,BOS,22.0,41,24,17,0.585,10.8,1.3,3.5,0.378,0.5,2.2,0.236,0.4,0.5,0.842,0.3,1.4,1.7,0.3,0.6,0.3,0.1,1.3,3.5,0.4
4,1630598,34,Aaron Wiggins,0.265,104.0,108.1,-4.2,0.073,1.41,9.6,0.561,0.036,0.103,0.070,0.534,0.063,0.134,0.561,100.75,1591,Aaron Wiggins,Aaron,1610612760,OKC,23.0,34,9,25,0.265,22.4,2.6,5.7,0.464,0.8,2.6,0.307,1.1,1.5,0.706,0.9,2.5,3.4,1.1,0.8,0.7,0.2,2.0,7.1,-2.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
587,1628380,5,Zach Collins,0.600,103.4,103.9,-0.5,0.183,1.38,16.7,0.504,0.090,0.200,0.145,0.500,0.093,0.186,0.504,104.46,177,Zach Collins,Zach,1610612759,SAS,24.0,5,3,2,0.600,16.4,2.4,5.4,0.444,0.6,1.4,0.429,0.4,0.8,0.500,1.6,3.6,5.2,2.2,1.6,0.8,0.4,2.2,5.8,-0.6
588,203897,47,Zach LaVine,0.660,113.2,110.7,2.5,0.206,1.63,10.1,0.606,0.008,0.128,0.070,0.561,0.131,0.287,0.606,99.85,3386,Zach LaVine,Zach,1610612741,CHI,27.0,47,31,16,0.660,34.6,8.7,18.1,0.482,2.9,7.2,0.399,4.2,4.9,0.869,0.3,4.6,4.9,4.5,2.7,0.6,0.4,1.7,24.6,2.1
589,1630192,39,Zeke Nnaji,0.590,108.1,110.8,-2.7,0.035,0.71,8.7,0.652,0.081,0.146,0.112,0.645,0.083,0.148,0.652,98.94,1341,Zeke Nnaji,Zeke,1610612743,DEN,21.0,39,23,16,0.590,16.7,2.4,4.5,0.540,0.9,1.9,0.487,1.0,1.6,0.613,1.4,2.3,3.7,0.4,0.5,0.3,0.3,1.9,6.8,-1.0
590,1630533,40,Ziaire Williams,0.650,111.6,110.0,1.6,0.053,1.52,7.0,0.535,0.011,0.064,0.037,0.521,0.044,0.138,0.535,101.88,1829,Ziaire Williams,Ziaire,1610612763,MEM,20.0,40,26,14,0.650,21.5,2.9,6.5,0.441,1.1,3.7,0.284,0.5,0.6,0.760,0.3,1.5,1.8,0.9,0.6,0.6,0.2,2.0,7.3,0.8
591,1629597,1,Zylan Cheatham,0.000,18.2,125.0,-106.8,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.000,-0.167,0.250,0.000,106.50,11,Zylan Cheatham,Zylan,1610612762,UTA,26.0,1,0,1,0.000,5.2,0.0,3.0,0.000,0.0,2.0,0.000,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-13.0

In [ ]:
all_star_data_2022.to_csv('all_star_data_2022.csv', index=False)

#new dfs 2021-2012

In [ ]:
season_id = '2020-21'
per_mode = 'PerGame'
player_info_url = 'https://stats.nba.com/stats/leaguedashplayerstats?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&GameSegment=&Height=&LastNGames=0&LeagueID=00&Location=&MeasureType=Base&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode='+per_mode+'&Period=0&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season='+season_id+'&SeasonSegment=Pre+All-Star&SeasonType=Regular+Season&ShotClockRange=&StarterBench=&TeamID=0&TwoWay=0&VsConference=&VsDivision=&Weight='
response = requests.get(url=player_info_url, headers=headers).json()
player_info = response['resultSets'][0]['rowSet']
trad_22 = pd.DataFrame(player_info, columns=columns_list)
real_trad_22 = trad_22[["PLAYER_ID","PLAYER_NAME","NICKNAME","TEAM_ID","TEAM_ABBREVIATION","AGE","GP","W","L","W_PCT","MIN","FGM","FGA","FG_PCT","FG3M","FG3A","FG3_PCT","FTM","FTA","FT_PCT","OREB","DREB","REB","AST","TOV","STL","BLK","PF","PTS","PLUS_MINUS"]]
player_info_url_adv = 'https://stats.nba.com/stats/leaguedashplayerstats?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&GameSegment=&Height=&LastNGames=0&LeagueID=00&Location=&MeasureType=Advanced&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode='+per_mode+'&Period=0&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season='+season_id+'&SeasonSegment=Pre+All-Star&SeasonType=Regular+Season&ShotClockRange=&StarterBench=&TeamID=0&TwoWay=0&VsConference=&VsDivision=&Weight='
response_adv = requests.get(url=player_info_url_adv, headers=headers).json()
player_info_adv = response_adv['resultSets'][0]['rowSet']
trad_2_adv = pd.DataFrame(player_info_adv, columns=columns_list_adv)
real_trad_2_adv = trad_2_adv[['PLAYER_ID','GP', 'PLAYER_NAME','W_PCT','OFF_RATING','DEF_RATING','NET_RATING','AST_PCT','AST_TO','TM_TOV_PCT',"TS_PCT","OREB_PCT","DREB_PCT","REB_PCT",'EFG_PCT',"PIE","USG_PCT","TS_PCT","PACE","POSS"]]
all_star_data_2021 = pd.merge(real_trad_2_adv, real_trad_22, how='inner', on = 'PLAYER_ID')
all_star_data_2021.head()

,PLAYER_ID,GP_x,PLAYER_NAME_x,W_PCT_x,OFF_RATING,DEF_RATING,NET_RATING,AST_PCT,AST_TO,TM_TOV_PCT,TS_PCT,OREB_PCT,DREB_PCT,REB_PCT,EFG_PCT,PIE,USG_PCT,TS_PCT,PACE,POSS,PLAYER_NAME_y,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP_y,W,L,W_PCT_y,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,TOV,STL,BLK,PF,PTS,PLUS_MINUS
0,203932,19,Aaron Gordon,0.421,104.9,109.5,-4.6,0.225,1.51,13.8,0.528,0.055,0.194,0.120,0.500,0.108,0.230,0.528,100.34,1160,Aaron Gordon,Aaron,1610612743,DEN,25.0,19,8,11,0.421,29.1,4.8,11.2,0.427,1.6,4.4,0.369,2.6,4.2,0.613,1.7,5.5,7.2,4.2,2.8,0.7,0.8,2.0,13.8,-2.1
1,1628988,35,Aaron Holiday,0.457,111.1,111.1,0.0,0.126,2.17,7.9,0.470,0.010,0.058,0.034,0.445,0.043,0.190,0.470,102.98,1434,Aaron Holiday,Aaron,1610612754,IND,24.0,35,16,19,0.457,19.1,2.7,7.3,0.371,1.1,3.1,0.352,0.8,1.1,0.725,0.2,1.1,1.3,1.8,0.8,0.6,0.1,1.8,7.3,0.2
2,1630174,18,Aaron Nesmith,0.500,110.8,107.3,3.5,0.032,0.64,12.8,0.549,0.035,0.120,0.078,0.532,0.034,0.116,0.549,101.40,595,Aaron Nesmith,Aaron,1610612738,BOS,21.0,18,9,9,0.500,15.6,1.4,3.5,0.397,0.9,2.7,0.354,0.4,0.7,0.667,0.6,1.9,2.4,0.4,0.6,0.2,0.3,2.1,4.2,1.4
3,1627846,19,Abdel Nader,0.684,106.4,99.7,6.7,0.079,1.15,10.1,0.599,0.011,0.153,0.084,0.561,0.093,0.181,0.599,101.98,578,Abdel Nader,Abdel,1610612756,PHX,27.0,19,13,6,0.684,14.4,2.3,4.7,0.489,0.7,1.7,0.394,1.1,1.3,0.800,0.2,2.3,2.4,0.8,0.7,0.3,0.4,1.3,6.4,1.8
4,1629690,7,Adam Mokoka,0.143,83.0,94.7,-11.7,0.182,2.00,10.0,0.393,0.021,0.079,0.047,0.393,0.040,0.152,0.393,106.50,94,Adam Mokoka,Adam,1610612741,CHI,22.0,7,1,6,0.143,6.1,0.7,2.0,0.357,0.1,1.1,0.125,0.0,0.0,0.000,0.1,0.4,0.6,0.6,0.3,0.3,0.1,0.7,1.6,-1.6

In [ ]:
season_id = '2019-20'
per_mode = 'PerGame'
player_info_url = 'https://stats.nba.com/stats/leaguedashplayerstats?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&GameSegment=&Height=&LastNGames=0&LeagueID=00&Location=&MeasureType=Base&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode='+per_mode+'&Period=0&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season='+season_id+'&SeasonSegment=Pre+All-Star&SeasonType=Regular+Season&ShotClockRange=&StarterBench=&TeamID=0&TwoWay=0&VsConference=&VsDivision=&Weight='
response = requests.get(url=player_info_url, headers=headers).json()
player_info = response['resultSets'][0]['rowSet']
trad_22 = pd.DataFrame(player_info, columns=columns_list)
real_trad_22 = trad_22[["PLAYER_ID","PLAYER_NAME","NICKNAME","TEAM_ID","TEAM_ABBREVIATION","AGE","GP","W","L","W_PCT","MIN","FGM","FGA","FG_PCT","FG3M","FG3A","FG3_PCT","FTM","FTA","FT_PCT","OREB","DREB","REB","AST","TOV","STL","BLK","PF","PTS","PLUS_MINUS"]]
player_info_url_adv = 'https://stats.nba.com/stats/leaguedashplayerstats?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&GameSegment=&Height=&LastNGames=0&LeagueID=00&Location=&MeasureType=Advanced&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode='+per_mode+'&Period=0&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season='+season_id+'&SeasonSegment=Pre+All-Star&SeasonType=Regular+Season&ShotClockRange=&StarterBench=&TeamID=0&TwoWay=0&VsConference=&VsDivision=&Weight='
response_adv = requests.get(url=player_info_url_adv, headers=headers).json()
player_info_adv = response_adv['resultSets'][0]['rowSet']
trad_2_adv = pd.DataFrame(player_info_adv, columns=columns_list_adv)
real_trad_2_adv = trad_2_adv[['PLAYER_ID','GP', 'PLAYER_NAME','W_PCT','OFF_RATING','DEF_RATING','NET_RATING','AST_PCT','AST_TO','TM_TOV_PCT',"TS_PCT","OREB_PCT","DREB_PCT","REB_PCT",'EFG_PCT',"PIE","USG_PCT","TS_PCT","PACE","POSS"]]
all_star_data_2020 = pd.merge(real_trad_2_adv, real_trad_22, how='inner', on = 'PLAYER_ID')
all_star_data_2020.head()

,PLAYER_ID,GP_x,PLAYER_NAME_x,W_PCT_x,OFF_RATING,DEF_RATING,NET_RATING,AST_PCT,AST_TO,TM_TOV_PCT,TS_PCT,OREB_PCT,DREB_PCT,REB_PCT,EFG_PCT,PIE,USG_PCT,TS_PCT,PACE,POSS,PLAYER_NAME_y,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP_y,W,L,W_PCT_y,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,TOV,STL,BLK,PF,PTS,PLUS_MINUS
0,203932,49,Aaron Gordon,0.449,105.7,109.2,-3.5,0.149,2.03,8.3,0.504,0.050,0.172,0.109,0.473,0.098,0.207,0.504,98.86,3249,Aaron Gordon,Aaron,1610612753,ORL,24.0,49,22,27,0.449,32.2,5.3,12.6,0.424,1.2,4.0,0.308,2.3,3.4,0.675,1.7,5.6,7.3,3.1,1.6,0.8,0.5,2.0,14.2,-2.6
1,1628988,49,Aaron Holiday,0.612,111.0,108.2,2.8,0.205,2.71,9.0,0.525,0.016,0.077,0.047,0.500,0.082,0.200,0.525,99.77,2334,Aaron Holiday,Aaron,1610612754,IND,23.0,49,30,19,0.612,22.8,3.7,8.9,0.415,1.5,3.7,0.413,1.0,1.1,0.870,0.4,1.8,2.2,3.4,1.3,0.7,0.2,1.8,9.9,1.9
2,1627846,39,Abdel Nader,0.667,98.5,103.0,-4.5,0.065,0.78,13.0,0.580,0.016,0.084,0.050,0.544,0.065,0.162,0.580,101.73,1248,Abdel Nader,Abdel,1610612760,OKC,26.0,39,26,13,0.667,15.1,2.0,4.4,0.459,0.7,2.2,0.341,0.9,1.2,0.783,0.3,1.3,1.6,0.6,0.8,0.4,0.3,1.3,5.7,-1.5
3,1629690,6,Adam Mokoka,0.167,104.3,81.8,22.4,0.000,0.00,0.0,0.472,0.125,0.000,0.077,0.500,0.088,0.263,0.472,100.03,47,Adam Mokoka,Adam,1610612741,CHI,21.0,6,1,5,0.167,3.6,1.0,2.5,0.400,0.5,1.2,0.429,0.0,0.3,0.000,0.7,0.0,0.7,0.0,0.0,0.2,0.0,0.2,2.5,2.2
4,1629678,26,Admiral Schofield,0.308,104.2,108.7,-4.6,0.068,2.00,6.9,0.514,0.018,0.092,0.054,0.493,0.037,0.124,0.514,103.17,626,Admiral Schofield,Admiral,1610612764,WAS,23.0,26,8,18,0.308,11.2,1.2,2.9,0.400,0.5,1.8,0.298,0.3,0.5,0.692,0.2,1.1,1.3,0.5,0.3,0.3,0.1,1.6,3.2,-1.2

In [ ]:
season_id = '2018-19'
per_mode = 'PerGame'
player_info_url = 'https://stats.nba.com/stats/leaguedashplayerstats?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&GameSegment=&Height=&LastNGames=0&LeagueID=00&Location=&MeasureType=Base&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode='+per_mode+'&Period=0&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season='+season_id+'&SeasonSegment=Pre+All-Star&SeasonType=Regular+Season&ShotClockRange=&StarterBench=&TeamID=0&TwoWay=0&VsConference=&VsDivision=&Weight='
response = requests.get(url=player_info_url, headers=headers).json()
player_info = response['resultSets'][0]['rowSet']
trad_22 = pd.DataFrame(player_info, columns=columns_list)
real_trad_22 = trad_22[["PLAYER_ID","PLAYER_NAME","NICKNAME","TEAM_ID","TEAM_ABBREVIATION","AGE","GP","W","L","W_PCT","MIN","FGM","FGA","FG_PCT","FG3M","FG3A","FG3_PCT","FTM","FTA","FT_PCT","OREB","DREB","REB","AST","TOV","STL","BLK","PF","PTS","PLUS_MINUS"]]
player_info_url_adv = 'https://stats.nba.com/stats/leaguedashplayerstats?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&GameSegment=&Height=&LastNGames=0&LeagueID=00&Location=&MeasureType=Advanced&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode='+per_mode+'&Period=0&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season='+season_id+'&SeasonSegment=Pre+All-Star&SeasonType=Regular+Season&ShotClockRange=&StarterBench=&TeamID=0&TwoWay=0&VsConference=&VsDivision=&Weight='
response_adv = requests.get(url=player_info_url_adv, headers=headers).json()
player_info_adv = response_adv['resultSets'][0]['rowSet']
trad_2_adv = pd.DataFrame(player_info_adv, columns=columns_list_adv)
real_trad_2_adv = trad_2_adv[['PLAYER_ID','GP', 'PLAYER_NAME','W_PCT','OFF_RATING','DEF_RATING','NET_RATING','AST_PCT','AST_TO','TM_TOV_PCT',"TS_PCT","OREB_PCT","DREB_PCT","REB_PCT",'EFG_PCT',"PIE","USG_PCT","TS_PCT","PACE","POSS"]]
all_star_data_2019 = pd.merge(real_trad_2_adv, real_trad_22, how='inner', on = 'PLAYER_ID')
all_star_data_2019.to_csv('all_star_data_2019.csv', index=False)
all_star_data_2019.head()

,PLAYER_ID,GP_x,PLAYER_NAME_x,W_PCT_x,OFF_RATING,DEF_RATING,NET_RATING,AST_PCT,AST_TO,TM_TOV_PCT,TS_PCT,OREB_PCT,DREB_PCT,REB_PCT,EFG_PCT,PIE,USG_PCT,TS_PCT,PACE,POSS,PLAYER_NAME_y,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP_y,W,L,W_PCT_y,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,TOV,STL,BLK,PF,PTS,PLUS_MINUS
0,203932,55,Aaron Gordon,0.455,106.8,106.6,0.1,0.162,1.79,9.8,0.536,0.048,0.164,0.106,0.503,0.108,0.213,0.536,98.97,3798,Aaron Gordon,Aaron,1610612753,ORL,23.0,55,25,30,0.455,33.5,5.9,13.2,0.446,1.5,4.4,0.342,2.5,3.4,0.731,1.7,5.6,7.3,3.5,2.0,0.8,0.7,2.3,15.8,0.2
1,1628988,37,Aaron Holiday,0.676,104.8,99.4,5.5,0.177,2.15,9.1,0.495,0.009,0.108,0.059,0.455,0.082,0.216,0.495,103.42,949,Aaron Holiday,Aaron,1610612754,IND,22.0,37,25,12,0.676,11.8,2.0,5.2,0.382,0.8,2.6,0.295,0.8,0.9,0.882,0.1,1.4,1.5,1.5,0.7,0.4,0.3,1.3,5.5,1.6
2,1627846,38,Abdel Nader,0.737,97.8,109.5,-11.7,0.039,0.67,9.6,0.551,0.017,0.144,0.080,0.532,0.069,0.155,0.551,106.07,846,Abdel Nader,Abdel,1610612760,OKC,25.0,38,28,10,0.737,10.1,1.5,3.3,0.464,0.4,1.3,0.354,0.4,0.5,0.737,0.2,1.6,1.8,0.3,0.4,0.2,0.1,1.1,3.9,-2.8
3,201143,48,Al Horford,0.625,112.6,107.1,5.4,0.197,2.51,9.8,0.598,0.067,0.160,0.115,0.584,0.128,0.183,0.598,100.49,2869,Al Horford,Al,1610612738,BOS,33.0,48,30,18,0.625,28.5,5.4,10.2,0.528,1.1,3.1,0.369,0.8,1.0,0.800,1.9,4.9,6.8,4.0,1.6,0.9,1.4,1.9,12.7,3.3
4,202329,57,Al-Farouq Aminu,0.596,115.7,108.8,7.0,0.057,1.63,7.8,0.577,0.051,0.207,0.130,0.524,0.098,0.128,0.577,101.42,3493,Al-Farouq Aminu,Al-Farouq,1610612757,POR,28.0,57,34,23,0.596,29.0,3.1,7.2,0.435,1.3,3.6,0.358,1.9,2.2,0.849,1.5,6.4,7.9,1.3,0.8,0.9,0.4,1.9,9.4,4.1

In [ ]:
season_id = '2017-18'
per_mode = 'PerGame'
player_info_url = 'https://stats.nba.com/stats/leaguedashplayerstats?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&GameSegment=&Height=&LastNGames=0&LeagueID=00&Location=&MeasureType=Base&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode='+per_mode+'&Period=0&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season='+season_id+'&SeasonSegment=Pre+All-Star&SeasonType=Regular+Season&ShotClockRange=&StarterBench=&TeamID=0&TwoWay=0&VsConference=&VsDivision=&Weight='
response = requests.get(url=player_info_url, headers=headers).json()
player_info = response['resultSets'][0]['rowSet']
trad_22 = pd.DataFrame(player_info, columns=columns_list)
real_trad_22 = trad_22[["PLAYER_ID","PLAYER_NAME","NICKNAME","TEAM_ID","TEAM_ABBREVIATION","AGE","GP","W","L","W_PCT","MIN","FGM","FGA","FG_PCT","FG3M","FG3A","FG3_PCT","FTM","FTA","FT_PCT","OREB","DREB","REB","AST","TOV","STL","BLK","PF","PTS","PLUS_MINUS"]]
player_info_url_adv = 'https://stats.nba.com/stats/leaguedashplayerstats?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&GameSegment=&Height=&LastNGames=0&LeagueID=00&Location=&MeasureType=Advanced&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode='+per_mode+'&Period=0&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season='+season_id+'&SeasonSegment=Pre+All-Star&SeasonType=Regular+Season&ShotClockRange=&StarterBench=&TeamID=0&TwoWay=0&VsConference=&VsDivision=&Weight='
response_adv = requests.get(url=player_info_url_adv, headers=headers).json()
player_info_adv = response_adv['resultSets'][0]['rowSet']
trad_2_adv = pd.DataFrame(player_info_adv, columns=columns_list_adv)
real_trad_2_adv = trad_2_adv[['PLAYER_ID','GP', 'PLAYER_NAME','W_PCT','OFF_RATING','DEF_RATING','NET_RATING','AST_PCT','AST_TO','TM_TOV_PCT',"TS_PCT","OREB_PCT","DREB_PCT","REB_PCT",'EFG_PCT',"PIE","USG_PCT","TS_PCT","PACE","POSS"]]
all_star_data_2018 = pd.merge(real_trad_2_adv, real_trad_22, how='inner', on = 'PLAYER_ID')
all_star_data_2018.head()

,PLAYER_ID,GP_x,PLAYER_NAME_x,W_PCT_x,OFF_RATING,DEF_RATING,NET_RATING,AST_PCT,AST_TO,TM_TOV_PCT,TS_PCT,OREB_PCT,DREB_PCT,REB_PCT,EFG_PCT,PIE,USG_PCT,TS_PCT,PACE,POSS,PLAYER_NAME_y,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP_y,W,L,W_PCT_y,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,TOV,STL,BLK,PF,PTS,PLUS_MINUS
0,201166,27,Aaron Brooks,0.593,98.5,116.9,-18.5,0.171,2.00,11.1,0.513,0.032,0.055,0.043,0.500,0.052,0.173,0.513,99.54,324,Aaron Brooks,Aaron,1610612750,MIN,33.0,27,16,11,0.593,5.8,0.8,1.9,0.431,0.3,0.8,0.333,0.1,0.2,0.667,0.2,0.3,0.5,0.7,0.3,0.2,0.0,0.7,2.0,-2.5
1,203932,39,Aaron Gordon,0.333,107.7,111.3,-3.5,0.097,1.12,9.3,0.547,0.048,0.194,0.120,0.515,0.113,0.233,0.547,101.00,2787,Aaron Gordon,Aaron,1610612753,ORL,22.0,39,13,26,0.333,34.0,6.7,15.0,0.447,2.0,5.8,0.346,3.0,4.2,0.718,1.7,6.6,8.3,2.2,1.9,0.9,0.7,2.0,18.4,-2.6
2,1627846,28,Abdel Nader,0.714,95.3,107.4,-12.1,0.106,0.89,16.1,0.441,0.029,0.103,0.065,0.436,0.032,0.163,0.441,99.49,552,Abdel Nader,Abdel,1610612738,BOS,24.0,28,20,8,0.714,9.5,1.0,2.8,0.346,0.5,1.4,0.359,0.2,0.4,0.455,0.3,1.0,1.3,0.6,0.7,0.2,0.1,0.8,2.6,-2.4
3,203940,5,Adreian Payne,0.000,103.5,115.9,-12.4,0.000,0.00,13.3,0.831,0.044,0.226,0.118,0.800,0.120,0.155,0.831,98.15,86,Adreian Payne,Adreian,1610612753,ORL,27.0,5,0,5,0.000,8.5,1.4,2.0,0.700,0.4,0.6,0.667,1.0,1.2,0.833,0.4,1.4,1.8,0.0,0.4,0.4,0.0,1.2,4.2,-2.6
4,201143,54,Al Horford,0.648,107.7,101.4,6.3,0.240,2.54,10.9,0.592,0.045,0.186,0.119,0.576,0.143,0.183,0.592,97.15,3523,Al Horford,Al,1610612738,BOS,32.0,54,35,19,0.648,32.2,5.4,10.5,0.508,1.4,3.3,0.436,1.1,1.5,0.735,1.4,6.3,7.7,5.1,2.0,0.6,1.1,2.0,13.3,4.2

In [ ]:
season_id = '2016-17'
per_mode = 'PerGame'
player_info_url = 'https://stats.nba.com/stats/leaguedashplayerstats?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&GameSegment=&Height=&LastNGames=0&LeagueID=00&Location=&MeasureType=Base&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode='+per_mode+'&Period=0&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season='+season_id+'&SeasonSegment=Pre+All-Star&SeasonType=Regular+Season&ShotClockRange=&StarterBench=&TeamID=0&TwoWay=0&VsConference=&VsDivision=&Weight='
response = requests.get(url=player_info_url, headers=headers).json()
player_info = response['resultSets'][0]['rowSet']
trad_22 = pd.DataFrame(player_info, columns=columns_list)
real_trad_22 = trad_22[["PLAYER_ID","PLAYER_NAME","NICKNAME","TEAM_ID","TEAM_ABBREVIATION","AGE","GP","W","L","W_PCT","MIN","FGM","FGA","FG_PCT","FG3M","FG3A","FG3_PCT","FTM","FTA","FT_PCT","OREB","DREB","REB","AST","TOV","STL","BLK","PF","PTS","PLUS_MINUS"]]
player_info_url_adv = 'https://stats.nba.com/stats/leaguedashplayerstats?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&GameSegment=&Height=&LastNGames=0&LeagueID=00&Location=&MeasureType=Advanced&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode='+per_mode+'&Period=0&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season='+season_id+'&SeasonSegment=Pre+All-Star&SeasonType=Regular+Season&ShotClockRange=&StarterBench=&TeamID=0&TwoWay=0&VsConference=&VsDivision=&Weight='
response_adv = requests.get(url=player_info_url_adv, headers=headers).json()
player_info_adv = response_adv['resultSets'][0]['rowSet']
trad_2_adv = pd.DataFrame(player_info_adv, columns=columns_list_adv)
real_trad_2_adv = trad_2_adv[['PLAYER_ID','GP', 'PLAYER_NAME','W_PCT','OFF_RATING','DEF_RATING','NET_RATING','AST_PCT','AST_TO','TM_TOV_PCT',"TS_PCT","OREB_PCT","DREB_PCT","REB_PCT",'EFG_PCT',"PIE","USG_PCT","TS_PCT","PACE","POSS"]]
all_star_data_2017 = pd.merge(real_trad_2_adv, real_trad_22, how='inner', on = 'PLAYER_ID')
all_star_data_2017.head()

,PLAYER_ID,GP_x,PLAYER_NAME_x,W_PCT_x,OFF_RATING,DEF_RATING,NET_RATING,AST_PCT,AST_TO,TM_TOV_PCT,TS_PCT,OREB_PCT,DREB_PCT,REB_PCT,EFG_PCT,PIE,USG_PCT,TS_PCT,PACE,POSS,PLAYER_NAME_y,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP_y,W,L,W_PCT_y,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,TOV,STL,BLK,PF,PTS,PLUS_MINUS
0,1627773,17,AJ Hammons,0.176,112.6,90.9,21.7,0.037,0.67,9.4,0.455,0.060,0.195,0.125,0.500,0.046,0.161,0.455,101.07,159,AJ Hammons,AJ,1610612742,DAL,24.0,17,3,14,0.176,4.5,0.5,1.3,0.409,0.2,0.4,0.667,0.1,0.6,0.200,0.3,0.9,1.2,0.1,0.2,0.0,0.4,0.6,1.4,1.8
1,201166,46,Aaron Brooks,0.565,102.7,103.2,-0.5,0.230,2.00,12.9,0.505,0.020,0.057,0.038,0.482,0.069,0.189,0.505,97.46,1340,Aaron Brooks,Aaron,1610612754,IND,32.0,46,26,20,0.565,14.3,2.0,4.9,0.407,0.7,2.2,0.337,0.5,0.6,0.793,0.3,0.8,1.1,2.2,1.1,0.5,0.2,1.4,5.2,-0.2
2,203932,56,Aaron Gordon,0.375,105.3,110.0,-4.7,0.106,1.76,7.8,0.503,0.046,0.119,0.082,0.478,0.078,0.193,0.503,96.57,3110,Aaron Gordon,Aaron,1610612753,ORL,21.0,56,21,35,0.375,27.6,4.3,10.0,0.428,1.0,3.4,0.292,1.6,2.4,0.650,1.3,3.3,4.6,1.9,1.1,0.8,0.4,2.1,11.2,-2.8
3,1626151,5,Aaron Harrison,0.400,79.4,100.0,-20.6,0.375,0.00,0.0,0.102,0.000,0.176,0.083,0.000,0.000,0.132,0.102,95.61,34,Aaron Harrison,Aaron,1610612766,CHA,22.0,5,2,3,0.400,3.3,0.0,0.8,0.000,0.0,0.4,0.000,0.2,0.4,0.500,0.0,0.6,0.6,0.6,0.0,0.0,0.0,0.4,0.2,-1.0
4,203940,12,Adreian Payne,0.333,96.8,106.9,-10.1,0.083,0.57,12.3,0.526,0.062,0.161,0.109,0.462,0.075,0.247,0.526,97.83,188,Adreian Payne,Adreian,1610612750,MIN,26.0,12,4,8,0.333,7.7,1.4,3.3,0.436,0.2,0.8,0.200,1.0,1.3,0.800,0.5,1.2,1.7,0.3,0.6,0.4,0.3,1.8,4.0,-1.7

In [ ]:
season_id = '2015-16'
per_mode = 'PerGame'
player_info_url = 'https://stats.nba.com/stats/leaguedashplayerstats?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&GameSegment=&Height=&LastNGames=0&LeagueID=00&Location=&MeasureType=Base&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode='+per_mode+'&Period=0&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season='+season_id+'&SeasonSegment=Pre+All-Star&SeasonType=Regular+Season&ShotClockRange=&StarterBench=&TeamID=0&TwoWay=0&VsConference=&VsDivision=&Weight='
response = requests.get(url=player_info_url, headers=headers).json()
player_info = response['resultSets'][0]['rowSet']
trad_22 = pd.DataFrame(player_info, columns=columns_list)
real_trad_22 = trad_22[["PLAYER_ID","PLAYER_NAME","NICKNAME","TEAM_ID","TEAM_ABBREVIATION","AGE","GP","W","L","W_PCT","MIN","FGM","FGA","FG_PCT","FG3M","FG3A","FG3_PCT","FTM","FTA","FT_PCT","OREB","DREB","REB","AST","TOV","STL","BLK","PF","PTS","PLUS_MINUS"]]
player_info_url_adv = 'https://stats.nba.com/stats/leaguedashplayerstats?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&GameSegment=&Height=&LastNGames=0&LeagueID=00&Location=&MeasureType=Advanced&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode='+per_mode+'&Period=0&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season='+season_id+'&SeasonSegment=Pre+All-Star&SeasonType=Regular+Season&ShotClockRange=&StarterBench=&TeamID=0&TwoWay=0&VsConference=&VsDivision=&Weight='
response_adv = requests.get(url=player_info_url_adv, headers=headers).json()
player_info_adv = response_adv['resultSets'][0]['rowSet']
trad_2_adv = pd.DataFrame(player_info_adv, columns=columns_list_adv)
real_trad_2_adv = trad_2_adv[['PLAYER_ID','GP', 'PLAYER_NAME','W_PCT','OFF_RATING','DEF_RATING','NET_RATING','AST_PCT','AST_TO','TM_TOV_PCT',"TS_PCT","OREB_PCT","DREB_PCT","REB_PCT",'EFG_PCT',"PIE","USG_PCT","TS_PCT","PACE","POSS"]]
all_star_data_2016 = pd.merge(real_trad_2_adv, real_trad_22, how='inner', on = 'PLAYER_ID')
all_star_data_2016.head()

,PLAYER_ID,GP_x,PLAYER_NAME_x,W_PCT_x,OFF_RATING,DEF_RATING,NET_RATING,AST_PCT,AST_TO,TM_TOV_PCT,TS_PCT,OREB_PCT,DREB_PCT,REB_PCT,EFG_PCT,PIE,USG_PCT,TS_PCT,PACE,POSS,PLAYER_NAME_y,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP_y,W,L,W_PCT_y,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,TOV,STL,BLK,PF,PTS,PLUS_MINUS
0,201166,42,Aaron Brooks,0.524,104.1,101.2,3.0,0.236,2.36,9.5,0.492,0.021,0.079,0.050,0.467,0.074,0.220,0.492,97.32,1351,Aaron Brooks,Aaron,1610612741,CHI,31.0,42,22,20,0.524,15.9,2.7,6.8,0.394,1.0,2.8,0.362,0.7,0.9,0.833,0.4,1.4,1.7,2.4,1.0,0.4,0.2,2.1,7.1,0.9
1,203932,51,Aaron Gordon,0.431,100.9,102.3,-1.5,0.102,1.74,8.8,0.539,0.085,0.189,0.136,0.502,0.115,0.160,0.539,96.68,2225,Aaron Gordon,Aaron,1610612753,ORL,20.0,51,22,29,0.431,21.8,2.9,6.2,0.465,0.5,1.5,0.299,1.5,2.2,0.684,1.9,4.2,6.1,1.4,0.8,0.6,0.8,1.8,7.7,-1.2
2,1626151,13,Aaron Harrison,0.615,91.9,91.1,0.7,0.000,0.00,13.3,0.277,0.053,0.094,0.073,0.250,0.003,0.116,0.277,107.59,123,Aaron Harrison,Aaron,1610612766,CHA,21.0,13,8,5,0.615,4.2,0.2,0.8,0.200,0.1,0.2,0.333,0.2,0.5,0.333,0.2,0.4,0.6,0.0,0.2,0.3,0.0,0.2,0.5,0.0
3,203940,33,Adreian Payne,0.364,98.4,106.2,-7.8,0.081,0.76,16.2,0.477,0.032,0.183,0.111,0.460,0.050,0.162,0.477,97.35,630,Adreian Payne,Adreian,1610612750,MIN,25.0,33,12,21,0.364,9.4,1.1,2.6,0.414,0.2,0.7,0.348,0.2,0.4,0.667,0.3,1.7,2.0,0.5,0.6,0.3,0.2,1.5,2.7,-1.5
4,201143,55,Al Horford,0.564,102.8,100.2,2.6,0.164,2.36,7.3,0.564,0.062,0.149,0.107,0.546,0.132,0.207,0.564,99.20,3583,Al Horford,Al,1610612737,ATL,30.0,55,31,24,0.564,31.6,6.5,12.8,0.507,1.0,2.9,0.340,1.3,1.6,0.778,1.9,4.9,6.9,3.1,1.3,0.8,1.5,2.0,15.3,1.5

In [ ]:
season_id = '2014-15'
per_mode = 'PerGame'
player_info_url = 'https://stats.nba.com/stats/leaguedashplayerstats?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&GameSegment=&Height=&LastNGames=0&LeagueID=00&Location=&MeasureType=Base&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode='+per_mode+'&Period=0&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season='+season_id+'&SeasonSegment=Pre+All-Star&SeasonType=Regular+Season&ShotClockRange=&StarterBench=&TeamID=0&TwoWay=0&VsConference=&VsDivision=&Weight='
response = requests.get(url=player_info_url, headers=headers).json()
player_info = response['resultSets'][0]['rowSet']
trad_22 = pd.DataFrame(player_info, columns=columns_list)
real_trad_22 = trad_22[["PLAYER_ID","PLAYER_NAME","NICKNAME","TEAM_ID","TEAM_ABBREVIATION","AGE","GP","W","L","W_PCT","MIN","FGM","FGA","FG_PCT","FG3M","FG3A","FG3_PCT","FTM","FTA","FT_PCT","OREB","DREB","REB","AST","TOV","STL","BLK","PF","PTS","PLUS_MINUS"]]
player_info_url_adv = 'https://stats.nba.com/stats/leaguedashplayerstats?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&GameSegment=&Height=&LastNGames=0&LeagueID=00&Location=&MeasureType=Advanced&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode='+per_mode+'&Period=0&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season='+season_id+'&SeasonSegment=Pre+All-Star&SeasonType=Regular+Season&ShotClockRange=&StarterBench=&TeamID=0&TwoWay=0&VsConference=&VsDivision=&Weight='
response_adv = requests.get(url=player_info_url_adv, headers=headers).json()
player_info_adv = response_adv['resultSets'][0]['rowSet']
trad_2_adv = pd.DataFrame(player_info_adv, columns=columns_list_adv)
real_trad_2_adv = trad_2_adv[['PLAYER_ID','GP', 'PLAYER_NAME','W_PCT','OFF_RATING','DEF_RATING','NET_RATING','AST_PCT','AST_TO','TM_TOV_PCT',"TS_PCT","OREB_PCT","DREB_PCT","REB_PCT",'EFG_PCT',"PIE","USG_PCT","TS_PCT","PACE","POSS"]]
all_star_data_2015 = pd.merge(real_trad_2_adv, real_trad_22, how='inner', on = 'PLAYER_ID')
all_star_data_2015.head()

,PLAYER_ID,GP_x,PLAYER_NAME_x,W_PCT_x,OFF_RATING,DEF_RATING,NET_RATING,AST_PCT,AST_TO,TM_TOV_PCT,TS_PCT,OREB_PCT,DREB_PCT,REB_PCT,EFG_PCT,PIE,USG_PCT,TS_PCT,PACE,POSS,PLAYER_NAME_y,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP_y,W,L,W_PCT_y,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,TOV,STL,BLK,PF,PTS,PLUS_MINUS
0,201985,21,AJ Price,0.429,97.0,104.2,-7.2,0.255,3.08,7.0,0.475,0.019,0.087,0.051,0.451,0.106,0.229,0.475,92.83,540,AJ Price,AJ,1610612739,CLE,28.0,21,9,12,0.429,13.3,2.3,5.9,0.390,0.7,2.4,0.300,0.8,1.1,0.667,0.3,1.1,1.4,1.9,0.6,0.3,0.0,0.5,6.0,-2.0
1,201166,54,Aaron Brooks,0.630,108.5,104.1,4.4,0.242,1.46,13.2,0.567,0.017,0.075,0.047,0.527,0.099,0.250,0.567,94.92,2138,Aaron Brooks,Aaron,1610612741,CHI,30.0,54,34,20,0.630,20.0,3.8,8.7,0.441,1.5,3.4,0.442,1.7,1.9,0.865,0.3,1.5,1.8,2.7,1.9,0.6,0.2,2.3,10.8,2.0
2,203932,23,Aaron Gordon,0.261,98.7,108.3,-9.6,0.062,0.65,15.6,0.613,0.047,0.149,0.099,0.586,0.082,0.157,0.613,96.76,753,Aaron Gordon,Aaron,1610612753,ORL,19.0,23,6,17,0.261,16.4,2.2,4.0,0.538,0.4,0.8,0.474,1.1,1.7,0.667,0.7,2.4,3.2,0.7,1.0,0.3,0.4,1.7,5.9,-4.0
3,203940,3,Adreian Payne,0.667,69.2,124.3,-55.1,0.000,0.00,0.0,0.317,0.053,0.200,0.118,0.286,-0.007,0.195,0.317,94.92,39,Adreian Payne,Adreian,1610612750,MIN,24.0,3,2,1,0.667,6.4,0.7,2.3,0.286,0.0,0.3,0.000,0.3,0.7,0.500,0.3,1.0,1.3,0.0,0.0,0.3,0.0,1.3,1.7,-6.3
4,201143,52,Al Horford,0.788,108.5,101.8,6.7,0.185,2.57,7.1,0.572,0.061,0.178,0.124,0.550,0.148,0.222,0.572,95.56,3178,Al Horford,Al,1610612737,ATL,29.0,52,41,11,0.788,30.7,6.9,12.7,0.544,0.2,0.5,0.296,1.6,2.0,0.774,1.7,5.8,7.4,3.3,1.3,0.7,1.3,1.7,15.6,4.1

In [ ]:
season_id = '2013-14'
per_mode = 'PerGame'
player_info_url = 'https://stats.nba.com/stats/leaguedashplayerstats?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&GameSegment=&Height=&LastNGames=0&LeagueID=00&Location=&MeasureType=Base&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode='+per_mode+'&Period=0&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season='+season_id+'&SeasonSegment=Pre+All-Star&SeasonType=Regular+Season&ShotClockRange=&StarterBench=&TeamID=0&TwoWay=0&VsConference=&VsDivision=&Weight='
response = requests.get(url=player_info_url, headers=headers).json()
player_info = response['resultSets'][0]['rowSet']
trad_22 = pd.DataFrame(player_info, columns=columns_list)
real_trad_22 = trad_22[["PLAYER_ID","PLAYER_NAME","NICKNAME","TEAM_ID","TEAM_ABBREVIATION","AGE","GP","W","L","W_PCT","MIN","FGM","FGA","FG_PCT","FG3M","FG3A","FG3_PCT","FTM","FTA","FT_PCT","OREB","DREB","REB","AST","TOV","STL","BLK","PF","PTS","PLUS_MINUS"]]
player_info_url_adv = 'https://stats.nba.com/stats/leaguedashplayerstats?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&GameSegment=&Height=&LastNGames=0&LeagueID=00&Location=&MeasureType=Advanced&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode='+per_mode+'&Period=0&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season='+season_id+'&SeasonSegment=Pre+All-Star&SeasonType=Regular+Season&ShotClockRange=&StarterBench=&TeamID=0&TwoWay=0&VsConference=&VsDivision=&Weight='
response_adv = requests.get(url=player_info_url_adv, headers=headers).json()
player_info_adv = response_adv['resultSets'][0]['rowSet']
trad_2_adv = pd.DataFrame(player_info_adv, columns=columns_list_adv)
real_trad_2_adv = trad_2_adv[['PLAYER_ID','GP', 'PLAYER_NAME','W_PCT','OFF_RATING','DEF_RATING','NET_RATING','AST_PCT','AST_TO','TM_TOV_PCT',"TS_PCT","OREB_PCT","DREB_PCT","REB_PCT",'EFG_PCT',"PIE","USG_PCT","TS_PCT","PACE","POSS"]]
all_star_data_2014 = pd.merge(real_trad_2_adv, real_trad_22, how='inner', on = 'PLAYER_ID')
all_star_data_2014.head()

,PLAYER_ID,GP_x,PLAYER_NAME_x,W_PCT_x,OFF_RATING,DEF_RATING,NET_RATING,AST_PCT,AST_TO,TM_TOV_PCT,TS_PCT,OREB_PCT,DREB_PCT,REB_PCT,EFG_PCT,PIE,USG_PCT,TS_PCT,PACE,POSS,PLAYER_NAME_y,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP_y,W,L,W_PCT_y,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,TOV,STL,BLK,PF,PTS,PLUS_MINUS
0,201985,24,AJ Price,0.542,90.6,90.1,0.5,0.267,1.71,11.9,0.477,0.009,0.085,0.046,0.488,0.089,0.212,0.477,100.41,191,AJ Price,AJ,1610612750,MIN,27.0,24,13,11,0.542,3.8,0.7,1.7,0.425,0.2,0.8,0.278,0.0,0.1,0.000,0.0,0.4,0.4,0.5,0.3,0.0,0.0,0.2,1.6,0.0
1,201166,42,Aaron Brooks,0.714,104.1,105.2,-1.1,0.195,1.66,12.0,0.531,0.034,0.054,0.044,0.500,0.072,0.204,0.531,97.47,1447,Aaron Brooks,Aaron,1610612743,DEN,29.0,42,30,12,0.714,16.9,2.5,6.2,0.397,1.3,3.1,0.412,0.9,1.0,0.841,0.5,0.9,1.5,2.0,1.2,0.6,0.1,1.8,7.1,-0.2
2,201189,28,Aaron Gray,0.321,99.5,103.3,-3.8,0.094,0.69,26.8,0.433,0.117,0.182,0.150,0.409,0.030,0.125,0.433,96.73,546,Aaron Gray,Aaron,1610612758,SAC,29.0,28,9,19,0.321,9.7,0.6,1.6,0.409,0.0,0.0,0.000,0.3,0.6,0.500,1.1,1.8,2.9,0.6,0.9,0.2,0.2,1.8,1.6,-0.9
3,1733,7,Al Harrington,0.286,91.7,114.5,-22.8,0.109,0.78,12.7,0.499,0.000,0.085,0.040,0.481,0.039,0.218,0.499,97.44,265,Al Harrington,Al,1610612764,WAS,34.0,7,2,5,0.286,18.5,2.7,7.4,0.365,1.7,4.0,0.429,0.7,1.0,0.714,0.0,1.4,1.4,1.0,1.3,0.6,0.0,2.3,7.9,-8.1
4,201143,29,Al Horford,0.552,104.3,101.1,3.1,0.139,1.19,10.7,0.588,0.072,0.189,0.131,0.571,0.153,0.244,0.588,96.88,1939,Al Horford,Al,1610612737,ATL,28.0,29,16,13,0.552,33.0,8.2,14.5,0.567,0.1,0.4,0.364,2.0,2.9,0.682,2.3,6.1,8.4,2.6,2.2,0.9,1.5,1.9,18.6,2.5

In [ ]:
season_id = '2012-13'
per_mode = 'PerGame'
player_info_url = 'https://stats.nba.com/stats/leaguedashplayerstats?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&GameSegment=&Height=&LastNGames=0&LeagueID=00&Location=&MeasureType=Base&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode='+per_mode+'&Period=0&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season='+season_id+'&SeasonSegment=Pre+All-Star&SeasonType=Regular+Season&ShotClockRange=&StarterBench=&TeamID=0&TwoWay=0&VsConference=&VsDivision=&Weight='
response = requests.get(url=player_info_url, headers=headers).json()
player_info = response['resultSets'][0]['rowSet']
trad_22 = pd.DataFrame(player_info, columns=columns_list)
real_trad_22 = trad_22[["PLAYER_ID","PLAYER_NAME","NICKNAME","TEAM_ID","TEAM_ABBREVIATION","AGE","GP","W","L","W_PCT","MIN","FGM","FGA","FG_PCT","FG3M","FG3A","FG3_PCT","FTM","FTA","FT_PCT","OREB","DREB","REB","AST","TOV","STL","BLK","PF","PTS","PLUS_MINUS"]]
player_info_url_adv = 'https://stats.nba.com/stats/leaguedashplayerstats?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&GameSegment=&Height=&LastNGames=0&LeagueID=00&Location=&MeasureType=Advanced&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode='+per_mode+'&Period=0&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season='+season_id+'&SeasonSegment=Pre+All-Star&SeasonType=Regular+Season&ShotClockRange=&StarterBench=&TeamID=0&TwoWay=0&VsConference=&VsDivision=&Weight='
response_adv = requests.get(url=player_info_url_adv, headers=headers).json()
player_info_adv = response_adv['resultSets'][0]['rowSet']
trad_2_adv = pd.DataFrame(player_info_adv, columns=columns_list_adv)
real_trad_2_adv = trad_2_adv[['PLAYER_ID','GP', 'PLAYER_NAME','W_PCT','OFF_RATING','DEF_RATING','NET_RATING','AST_PCT','AST_TO','TM_TOV_PCT',"TS_PCT","OREB_PCT","DREB_PCT","REB_PCT",'EFG_PCT',"PIE","USG_PCT","TS_PCT","PACE","POSS"]]
all_star_data_2013 = pd.merge(real_trad_2_adv, real_trad_22, how='inner', on = 'PLAYER_ID')
all_star_data_2013.head()

,PLAYER_ID,GP_x,PLAYER_NAME_x,W_PCT_x,OFF_RATING,DEF_RATING,NET_RATING,AST_PCT,AST_TO,TM_TOV_PCT,TS_PCT,OREB_PCT,DREB_PCT,REB_PCT,EFG_PCT,PIE,USG_PCT,TS_PCT,PACE,POSS,PLAYER_NAME_y,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP_y,W,L,W_PCT_y,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,TOV,STL,BLK,PF,PTS,PLUS_MINUS
0,201985,36,AJ Price,0.361,97.6,100.5,-2.8,0.295,3.51,9.2,0.478,0.017,0.085,0.051,0.454,0.096,0.170,0.478,92.79,1614,AJ Price,AJ,1610612764,WAS,26.0,36,13,23,0.361,23.3,2.7,7.2,0.378,1.1,3.4,0.322,0.8,0.9,0.794,0.4,2.0,2.4,4.2,1.2,0.7,0.0,1.3,7.3,-1.7
1,201166,45,Aaron Brooks,0.333,101.7,112.0,-10.3,0.188,1.73,12.7,0.569,0.012,0.072,0.040,0.545,0.077,0.177,0.569,93.52,1847,Aaron Brooks,Aaron,1610612745,HOU,28.0,45,15,30,0.333,21.1,3.1,6.6,0.465,1.1,2.8,0.384,0.9,1.2,0.769,0.3,1.4,1.7,2.4,1.4,0.6,0.1,2.0,8.1,-4.4
2,201189,29,Aaron Gray,0.310,98.5,104.5,-6.1,0.092,0.68,22.0,0.552,0.100,0.187,0.142,0.542,0.052,0.149,0.552,94.06,717,Aaron Gray,Aaron,1610612761,TOR,28.0,29,9,20,0.310,12.7,1.3,2.5,0.542,0.0,0.0,0.000,0.7,1.2,0.528,1.2,2.1,3.4,0.7,1.1,0.2,0.1,2.2,3.3,-1.9
3,201143,48,Al Horford,0.583,105.8,101.9,3.9,0.147,1.78,9.1,0.553,0.074,0.196,0.137,0.541,0.137,0.206,0.553,92.11,3401,Al Horford,Al,1610612737,ATL,27.0,48,28,20,0.583,36.9,7.2,13.3,0.541,0.0,0.0,0.000,1.8,3.0,0.599,2.6,7.2,9.8,3.2,1.8,0.9,1.0,2.2,16.2,2.7
4,2744,53,Al Jefferson,0.547,106.4,108.7,-2.3,0.118,1.75,6.0,0.520,0.066,0.240,0.152,0.487,0.147,0.252,0.520,92.01,3342,Al Jefferson,Al,1610612762,UTA,28.0,53,29,24,0.547,32.9,7.6,15.6,0.485,0.0,0.2,0.154,2.4,2.9,0.813,2.1,7.4,9.5,2.1,1.2,1.0,1.2,2.3,17.5,-1.4

In [ ]:
season_id = '2011-12'
per_mode = 'PerGame'
player_info_url = 'https://stats.nba.com/stats/leaguedashplayerstats?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&GameSegment=&Height=&LastNGames=0&LeagueID=00&Location=&MeasureType=Base&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode='+per_mode+'&Period=0&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season='+season_id+'&SeasonSegment=Pre+All-Star&SeasonType=Regular+Season&ShotClockRange=&StarterBench=&TeamID=0&TwoWay=0&VsConference=&VsDivision=&Weight='
response = requests.get(url=player_info_url, headers=headers).json()
player_info = response['resultSets'][0]['rowSet']
trad_22 = pd.DataFrame(player_info, columns=columns_list)
real_trad_22 = trad_22[["PLAYER_ID","PLAYER_NAME","NICKNAME","TEAM_ID","TEAM_ABBREVIATION","AGE","GP","W","L","W_PCT","MIN","FGM","FGA","FG_PCT","FG3M","FG3A","FG3_PCT","FTM","FTA","FT_PCT","OREB","DREB","REB","AST","TOV","STL","BLK","PF","PTS","PLUS_MINUS"]]
player_info_url_adv = 'https://stats.nba.com/stats/leaguedashplayerstats?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&GameSegment=&Height=&LastNGames=0&LeagueID=00&Location=&MeasureType=Advanced&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode='+per_mode+'&Period=0&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season='+season_id+'&SeasonSegment=Pre+All-Star&SeasonType=Regular+Season&ShotClockRange=&StarterBench=&TeamID=0&TwoWay=0&VsConference=&VsDivision=&Weight='
response_adv = requests.get(url=player_info_url_adv, headers=headers).json()
player_info_adv = response_adv['resultSets'][0]['rowSet']
trad_2_adv = pd.DataFrame(player_info_adv, columns=columns_list_adv)
real_trad_2_adv = trad_2_adv[['PLAYER_ID','GP', 'PLAYER_NAME','W_PCT','OFF_RATING','DEF_RATING','NET_RATING','AST_PCT','AST_TO','TM_TOV_PCT',"TS_PCT","OREB_PCT","DREB_PCT","REB_PCT",'EFG_PCT',"PIE","USG_PCT","TS_PCT","PACE","POSS"]]
all_star_data_2012 = pd.merge(real_trad_2_adv, real_trad_22, how='inner', on = 'PLAYER_ID')
all_star_data_2012.head()

,PLAYER_ID,GP_x,PLAYER_NAME_x,W_PCT_x,OFF_RATING,DEF_RATING,NET_RATING,AST_PCT,AST_TO,TM_TOV_PCT,TS_PCT,OREB_PCT,DREB_PCT,REB_PCT,EFG_PCT,PIE,USG_PCT,TS_PCT,PACE,POSS,PLAYER_NAME_y,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP_y,W,L,W_PCT_y,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,TOV,STL,BLK,PF,PTS,PLUS_MINUS
0,201985,21,AJ Price,0.619,97.6,92.0,5.6,0.259,2.06,11.9,0.511,0.013,0.100,0.052,0.455,0.123,0.184,0.511,93.33,531,AJ Price,AJ,1610612754,IND,25.0,21,13,8,0.619,12.9,1.6,4.2,0.371,0.7,2.1,0.333,0.9,0.9,1.000,0.2,1.1,1.3,1.8,0.9,0.7,0.1,1.0,4.7,1.7
1,201189,17,Aaron Gray,0.294,92.4,106.7,-14.2,0.035,0.32,21.8,0.477,0.120,0.291,0.198,0.491,0.074,0.130,0.477,91.17,542,Aaron Gray,Aaron,1610612761,TOR,27.0,17,5,12,0.294,16.8,1.6,3.2,0.491,0.0,0.0,0.000,0.4,1.1,0.333,2.1,4.3,6.4,0.4,1.1,0.6,0.4,2.6,3.5,-4.4
2,1733,35,Al Harrington,0.514,106.0,100.8,5.2,0.093,0.71,12.2,0.537,0.045,0.180,0.113,0.513,0.106,0.247,0.537,96.60,1924,Al Harrington,Al,1610612743,DEN,32.0,35,18,17,0.514,27.3,5.5,12.0,0.455,1.4,4.5,0.308,2.0,3.1,0.664,1.2,4.9,6.1,1.5,2.1,1.0,0.2,2.9,14.3,2.9
3,201143,11,Al Horford,0.636,108.6,100.3,8.3,0.113,1.50,10.4,0.585,0.077,0.156,0.116,0.553,0.130,0.174,0.585,90.07,652,Al Horford,Al,1610612737,ATL,26.0,11,7,4,0.636,31.6,5.2,9.4,0.553,0.0,0.1,0.000,2.0,2.7,0.733,2.4,4.6,7.0,2.2,1.5,0.9,1.3,1.9,12.4,4.7
4,2744,29,Al Jefferson,0.448,105.9,106.0,-0.1,0.108,1.63,5.5,0.510,0.073,0.224,0.148,0.481,0.156,0.276,0.510,92.42,1830,Al Jefferson,Al,1610612762,UTA,27.0,29,13,16,0.448,32.9,8.3,17.3,0.481,0.0,0.1,0.000,2.4,3.2,0.761,2.3,7.1,9.4,2.0,1.2,0.9,1.6,2.5,19.1,-0.7

#adding Hustle

In [ ]:
Hustle_columns = ["PLAYER_ID",
"PLAYER_NAME",
"TEAM_ID",
"TEAM_ABBREVIATION",
"AGE",
"G",
"MIN",
"CONTESTED_SHOTS",
"CONTESTED_SHOTS_2PT",
"CONTESTED_SHOTS_3PT",
"DEFLECTIONS",
"CHARGES_DRAWN",
"SCREEN_ASSISTS",
"SCREEN_AST_PTS",
"OFF_LOOSE_BALLS_RECOVERED",
"DEF_LOOSE_BALLS_RECOVERED",
"LOOSE_BALLS_RECOVERED",
"PCT_LOOSE_BALLS_RECOVERED_OFF",
"PCT_LOOSE_BALLS_RECOVERED_DEF",
"OFF_BOXOUTS",
"DEF_BOXOUTS",
"BOX_OUTS",
"BOX_OUT_PLAYER_TEAM_REBS",
"BOX_OUT_PLAYER_REBS",
"PCT_BOX_OUTS_OFF",
"PCT_BOX_OUTS_DEF",
"PCT_BOX_OUTS_TEAM_REB",
"PCT_BOX_OUTS_REB"]

In [ ]:
season_id = '2021-22'
per_mode = 'PerGame'
hustle_url = 'https://stats.nba.com/stats/leaguehustlestatsplayer?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&Height=&LastNGames=0&LeagueID=00&Location=&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode='+per_mode+'&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season='+season_id+'&SeasonSegment=Pre+All-Star&SeasonType=Regular+Season&TeamID=0&VsConference=&VsDivision=&Weight='
response_hustle = requests.get(url=hustle_url, headers=headers).json()       
player_hustle = response_hustle['resultSets'][0]['rowSet']
playstyle_22 = pd.DataFrame(player_hustle, columns=Hustle_columns)    
playstyle_22

,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,AGE,G,MIN,CONTESTED_SHOTS,CONTESTED_SHOTS_2PT,CONTESTED_SHOTS_3PT,DEFLECTIONS,CHARGES_DRAWN,SCREEN_ASSISTS,SCREEN_AST_PTS,OFF_LOOSE_BALLS_RECOVERED,DEF_LOOSE_BALLS_RECOVERED,LOOSE_BALLS_RECOVERED,PCT_LOOSE_BALLS_RECOVERED_OFF,PCT_LOOSE_BALLS_RECOVERED_DEF,OFF_BOXOUTS,DEF_BOXOUTS,BOX_OUTS,BOX_OUT_PLAYER_TEAM_REBS,BOX_OUT_PLAYER_REBS,PCT_BOX_OUTS_OFF,PCT_BOX_OUTS_DEF,PCT_BOX_OUTS_TEAM_REB,PCT_BOX_OUTS_REB
0,203932,Aaron Gordon,1610612743,DEN,26.0,53,31.8,5.21,3.49,1.72,1.00,0.02,0.72,1.75,0.42,0.25,0.66,0.629,0.371,0.15,0.43,0.58,0.47,0.32,0.258,0.742,0.926,0.630
1,1630565,Aaron Henry,1610612755,PHI,22.0,6,2.8,0.83,0.50,0.33,0.17,0.00,0.00,0.00,0.00,0.00,0.00,0.000,0.000,0.00,0.17,0.17,0.00,0.00,0.000,1.000,0.000,0.000
2,1628988,Aaron Holiday,1610612756,PHX,25.0,44,16.0,2.55,1.34,1.20,1.30,0.00,0.14,0.36,0.16,0.18,0.34,0.467,0.533,0.02,0.34,0.36,0.34,0.02,0.063,0.938,0.938,0.063
3,1630174,Aaron Nesmith,1610612738,BOS,22.0,41,10.8,2.90,1.80,1.10,0.46,0.07,0.07,0.17,0.10,0.12,0.22,0.444,0.556,0.07,0.32,0.39,0.37,0.20,0.188,0.813,0.938,0.500
4,1630598,Aaron Wiggins,1610612760,OKC,23.0,34,22.4,5.24,2.79,2.44,1.50,0.00,0.35,0.76,0.18,0.35,0.53,0.333,0.667,0.03,0.50,0.53,0.47,0.18,0.056,0.944,0.941,0.353
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
587,1628380,Zach Collins,1610612759,SAS,24.0,5,16.4,7.00,5.40,1.60,0.80,0.00,2.80,5.80,0.00,0.00,0.00,0.000,0.000,0.20,1.40,1.60,1.20,0.60,0.125,0.875,1.000,0.500
588,203897,Zach LaVine,1610612741,CHI,27.0,47,34.6,5.79,2.38,3.40,0.98,0.02,0.51,1.09,0.40,0.30,0.70,0.576,0.424,0.02,0.28,0.30,0.30,0.15,0.071,0.929,1.000,0.500
589,1630192,Zeke Nnaji,1610612743,DEN,21.0,39,16.7,3.59,2.00,1.59,0.72,0.00,0.95,2.38,0.26,0.15,0.41,0.625,0.375,0.56,0.69,1.26,1.15,0.79,0.449,0.551,0.978,0.674
590,1630533,Ziaire Williams,1610612763,MEM,20.0,40,21.5,4.50,2.00,2.50,1.05,0.00,0.08,0.18,0.10,0.13,0.23,0.444,0.556,0.00,0.25,0.25,0.20,0.05,0.000,1.000,1.000,0.250
591,1629597,Zylan Cheatham,1610612762,UTA,26.0,1,5.2,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.000,0.000,0.00,0.00,0.00,0.00,0.00,0.000,0.000,0.000,0.000

In [ ]:
season_id = '2021-22'
per_mode = 'PerGame'
hustle_url = 'https://stats.nba.com/stats/leaguehustlestatsplayer?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&Height=&LastNGames=0&LeagueID=00&Location=&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode='+per_mode+'&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season='+season_id+'&SeasonSegment=Pre+All-Star&SeasonType=Regular+Season&TeamID=0&VsConference=&VsDivision=&Weight='
response_hustle = requests.get(url=hustle_url, headers=headers).json()       
player_hustle = response_hustle['resultSets'][0]['rowSet']
playstyle_22 = pd.DataFrame(player_hustle, columns=Hustle_columns)

In [ ]:
season_id = '2020-21'
per_mode = 'PerGame'
hustle_url = 'https://stats.nba.com/stats/leaguehustlestatsplayer?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&Height=&LastNGames=0&LeagueID=00&Location=&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode='+per_mode+'&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season='+season_id+'&SeasonSegment=Pre+All-Star&SeasonType=Regular+Season&TeamID=0&VsConference=&VsDivision=&Weight='
response_hustle = requests.get(url=hustle_url, headers=headers).json()       
player_hustle = response_hustle['resultSets'][0]['rowSet']
playstyle_21 = pd.DataFrame(player_hustle, columns=Hustle_columns)

In [ ]:
season_id = '2019-20'
per_mode = 'PerGame'
hustle_url = 'https://stats.nba.com/stats/leaguehustlestatsplayer?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&Height=&LastNGames=0&LeagueID=00&Location=&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode='+per_mode+'&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season='+season_id+'&SeasonSegment=Pre+All-Star&SeasonType=Regular+Season&TeamID=0&VsConference=&VsDivision=&Weight='
response_hustle = requests.get(url=hustle_url, headers=headers).json()       
player_hustle = response_hustle['resultSets'][0]['rowSet']
playstyle_20 = pd.DataFrame(player_hustle, columns=Hustle_columns)

In [ ]:
season_id = '2018-19'
per_mode = 'PerGame'
hustle_url = 'https://stats.nba.com/stats/leaguehustlestatsplayer?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&Height=&LastNGames=0&LeagueID=00&Location=&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode='+per_mode+'&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season='+season_id+'&SeasonSegment=Pre+All-Star&SeasonType=Regular+Season&TeamID=0&VsConference=&VsDivision=&Weight='
response_hustle = requests.get(url=hustle_url, headers=headers).json()       
player_hustle = response_hustle['resultSets'][0]['rowSet']
playstyle_19 = pd.DataFrame(player_hustle, columns=Hustle_columns)

In [ ]:
season_id = '2017-18'
per_mode = 'PerGame'
hustle_url = 'https://stats.nba.com/stats/leaguehustlestatsplayer?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&Height=&LastNGames=0&LeagueID=00&Location=&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode='+per_mode+'&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season='+season_id+'&SeasonSegment=Pre+All-Star&SeasonType=Regular+Season&TeamID=0&VsConference=&VsDivision=&Weight='
response_hustle = requests.get(url=hustle_url, headers=headers).json()       
player_hustle = response_hustle['resultSets'][0]['rowSet']
playstyle_18 = pd.DataFrame(player_hustle, columns=Hustle_columns)

In [ ]:
season_id = '2016-17'
per_mode = 'PerGame'
hustle_url = 'https://stats.nba.com/stats/leaguehustlestatsplayer?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&Height=&LastNGames=0&LeagueID=00&Location=&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode='+per_mode+'&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season='+season_id+'&SeasonSegment=Pre+All-Star&SeasonType=Regular+Season&TeamID=0&VsConference=&VsDivision=&Weight='
response_hustle = requests.get(url=hustle_url, headers=headers).json()       
player_hustle = response_hustle['resultSets'][0]['rowSet']
playstyle_17 = pd.DataFrame(player_hustle, columns=Hustle_columns)

In [ ]:
season_id = '2015-16'
per_mode = 'PerGame'
hustle_url = 'https://stats.nba.com/stats/leaguehustlestatsplayer?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&Height=&LastNGames=0&LeagueID=00&Location=&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode='+per_mode+'&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season='+season_id+'&SeasonSegment=Pre+All-Star&SeasonType=Regular+Season&TeamID=0&VsConference=&VsDivision=&Weight='
response_hustle = requests.get(url=hustle_url, headers=headers).json()       
player_hustle = response_hustle['resultSets'][0]['rowSet']
playstyle_16 = pd.DataFrame(player_hustle, columns=Hustle_columns)

In [ ]:
season_id = '2014-15'
per_mode = 'PerGame'
hustle_url = 'https://stats.nba.com/stats/leaguehustlestatsplayer?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&Height=&LastNGames=0&LeagueID=00&Location=&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode='+per_mode+'&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season='+season_id+'&SeasonSegment=Pre+All-Star&SeasonType=Regular+Season&TeamID=0&VsConference=&VsDivision=&Weight='
response_hustle = requests.get(url=hustle_url, headers=headers).json()       
player_hustle = response_hustle['resultSets'][0]['rowSet']
playstyle_15 = pd.DataFrame(player_hustle, columns=Hustle_columns)

In [ ]:
season_id = '2013-14'
per_mode = 'PerGame'
hustle_url = 'https://stats.nba.com/stats/leaguehustlestatsplayer?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&Height=&LastNGames=0&LeagueID=00&Location=&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode='+per_mode+'&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season='+season_id+'&SeasonSegment=Pre+All-Star&SeasonType=Regular+Season&TeamID=0&VsConference=&VsDivision=&Weight='
response_hustle = requests.get(url=hustle_url, headers=headers).json()       
player_hustle = response_hustle['resultSets'][0]['rowSet']
playstyle_14 = pd.DataFrame(player_hustle, columns=Hustle_columns)

In [ ]:
season_id = '2012-13'
per_mode = 'PerGame'
hustle_url = 'https://stats.nba.com/stats/leaguehustlestatsplayer?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&Height=&LastNGames=0&LeagueID=00&Location=&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode='+per_mode+'&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season='+season_id+'&SeasonSegment=Pre+All-Star&SeasonType=Regular+Season&TeamID=0&VsConference=&VsDivision=&Weight='
response_hustle = requests.get(url=hustle_url, headers=headers).json()       
player_hustle = response_hustle['resultSets'][0]['rowSet']
playstyle_13 = pd.DataFrame(player_hustle, columns=Hustle_columns)

In [ ]:
season_id = '2011-12'
per_mode = 'PerGame'
hustle_url = 'https://stats.nba.com/stats/leaguehustlestatsplayer?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&Height=&LastNGames=0&LeagueID=00&Location=&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode='+per_mode+'&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season='+season_id+'&SeasonSegment=Pre+All-Star&SeasonType=Regular+Season&TeamID=0&VsConference=&VsDivision=&Weight='
response_hustle = requests.get(url=hustle_url, headers=headers).json()       
player_hustle = response_hustle['resultSets'][0]['rowSet']
playstyle_12 = pd.DataFrame(player_hustle, columns=Hustle_columns)

#Joining

In [ ]:
allstar_data_2022 = pd.merge(all_star_data_2022, playstyle_22, how='left', on = 'PLAYER_ID')
allstar_data_2021 = pd.merge(all_star_data_2021, playstyle_21, how='left', on = 'PLAYER_ID')
allstar_data_2020 = pd.merge(all_star_data_2020, playstyle_20, how='left', on = 'PLAYER_ID')
allstar_data_2019 = pd.merge(all_star_data_2019, playstyle_19, how='left', on = 'PLAYER_ID')
allstar_data_2018 = pd.merge(all_star_data_2018, playstyle_18, how='left', on = 'PLAYER_ID')
allstar_data_2017 = pd.merge(all_star_data_2017, playstyle_17, how='left', on = 'PLAYER_ID')
allstar_data_2016 = pd.merge(all_star_data_2016, playstyle_16, how='left', on = 'PLAYER_ID')
allstar_data_2015 = pd.merge(all_star_data_2015, playstyle_15, how='left', on = 'PLAYER_ID')
allstar_data_2014 = pd.merge(all_star_data_2014, playstyle_14, how='left', on = 'PLAYER_ID')
allstar_data_2013 = pd.merge(all_star_data_2013, playstyle_13, how='left', on = 'PLAYER_ID')
allstar_data_2012 = pd.merge(all_star_data_2012, playstyle_12, how='left', on = 'PLAYER_ID')

In [ ]:
allstar_data_2012.insert(1,'year', 2012, True)
allstar_data_2013.insert(1,'year', 2013, True)
allstar_data_2014.insert(1,'year', 2014, True)
allstar_data_2015.insert(1,'year', 2015, True)
allstar_data_2016.insert(1,'year', 2016, True)
allstar_data_2017.insert(1,'year', 2017, True)
allstar_data_2018.insert(1,'year', 2018, True)
allstar_data_2019.insert(1,'year', 2019, True)
allstar_data_2020.insert(1,'year', 2020, True)
allstar_data_2021.insert(1,'year', 2021, True)
allstar_data_2022.insert(1,'year', 2022, True)

#position

In [ ]:
postion_columns = ["PERSON_ID", 
"PLAYER_LAST_NAME",
"PLAYER_FIRST_NAME",
"PLAYER_SLUG",
"TEAM_ID",
"TEAM_SLUG",
"IS_DEFUNCT",
"TEAM_CITY",
"TEAM_NAME",
"TEAM_ABBREVIATION",
"JERSEY_NUMBER",
"POSITION",
"HEIGHT",
"WEIGHT",
"COLLEGE",
"COUNTRY",
"DRAFT_YEAR",
"DRAFT_ROUND",
"DRAFT_NUMBER",
"ROSTER_STATUS",
"PTS",
"REB",
"AST",
"STATS_TIMEFRAME",
"FROM_YEAR",
"TO_YEAR"]

In [ ]:
position_url = 'https://stats.nba.com/stats/playerindex?College=&Country=&DraftPick=&DraftRound=&DraftYear=&Height=&Historical=1&LeagueID=00&Season=2021-22&SeasonType=Regular%20Season&TeamID=0&Weight='
response_position = requests.get(url=position_url, headers=headers).json()       
player_position = response_position['resultSets'][0]['rowSet']
position_all = pd.DataFrame(player_position, columns=postion_columns)

In [ ]:
position_all_real = position_all[['PERSON_ID',"POSITION"]]

In [ ]:
position_all_real = position_all_real.rename({'PERSON_ID': 'PLAYER_ID', 'POSITION': 'POSITION'}, axis=1) 
position_all_real

      PLAYER_ID POSITION
0         76001        F
1         76002        C
2         76003        C
3            51        G
4          1505      F-G
...         ...      ...
4726    1627790        C
4727      78647        C
4728      78648        G
4729    1627826        C
4730      78650        G

[4731 rows x 2 columns]

#Joining position with rest of data

In [ ]:
allstar_nba_data_2012 = pd.merge(allstar_data_2012, position_all_real, how='left', on = 'PLAYER_ID') 
allstar_nba_data_2013 = pd.merge(allstar_data_2013, position_all_real, how='left', on = 'PLAYER_ID') 
allstar_nba_data_2014 = pd.merge(allstar_data_2014, position_all_real, how='left', on = 'PLAYER_ID') 
allstar_nba_data_2015 = pd.merge(allstar_data_2015, position_all_real, how='left', on = 'PLAYER_ID') 
allstar_nba_data_2016 = pd.merge(allstar_data_2016, position_all_real, how='left', on = 'PLAYER_ID') 
allstar_nba_data_2017 = pd.merge(allstar_data_2017, position_all_real, how='left', on = 'PLAYER_ID') 
allstar_nba_data_2018 = pd.merge(allstar_data_2018, position_all_real, how='left', on = 'PLAYER_ID') 
allstar_nba_data_2019 = pd.merge(allstar_data_2019, position_all_real, how='left', on = 'PLAYER_ID') 
allstar_nba_data_2020 = pd.merge(allstar_data_2020, position_all_real, how='left', on = 'PLAYER_ID') 
allstar_nba_data_2021 = pd.merge(allstar_data_2021, position_all_real, how='left', on = 'PLAYER_ID') 
allstar_nba_data_2022 = pd.merge(allstar_data_2022, position_all_real, how='left', on = 'PLAYER_ID')

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/

In [ ]:
allstar_nba_data_2012.to_csv('/content/drive/MyDrive/Capstone/raw_allstar_2012.csv')
allstar_nba_data_2013.to_csv('/content/drive/MyDrive/Capstone/raw_allstar_2013.csv')
allstar_nba_data_2014.to_csv('/content/drive/MyDrive/Capstone/raw_allstar_2014.csv')
allstar_nba_data_2015.to_csv('/content/drive/MyDrive/Capstone/raw_allstar_2015.csv')
allstar_nba_data_2016.to_csv('/content/drive/MyDrive/Capstone/raw_allstar_2016.csv')
allstar_nba_data_2017.to_csv('/content/drive/MyDrive/Capstone/raw_allstar_2017.csv')
allstar_nba_data_2018.to_csv('/content/drive/MyDrive/Capstone/raw_allstar_2018.csv')
allstar_nba_data_2019.to_csv('/content/drive/MyDrive/Capstone/raw_allstar_2019.csv')
allstar_nba_data_2020.to_csv('/content/drive/MyDrive/Capstone/raw_allstar_2020.csv')
allstar_nba_data_2021.to_csv('/content/drive/MyDrive/Capstone/raw_allstar_2021.csv')
allstar_nba_data_2022.to_csv('/content/drive/MyDrive/Capstone/raw_allstar_2022.csv')

#-------

In [ ]:
new_allstar_df = all_nba_df[['PLAYER_ID', 'year', 'PLAYER_NAME_x', 'W_PCT_x','W', 'L', 'MIN_x', 'FGM', 'FGA',
       'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST',
       'TOV', 'STL', 'BLK', 'PF', 'PTS', 'PLUS_MINUS','OFF_RATING', 'DEF_RATING', 'NET_RATING',
       'AST_PCT', 'AST_TO', 'TM_TOV_PCT', 'TS_PCT', 'OREB_PCT', 'DREB_PCT', 'REB_PCT', 'EFG_PCT',
       'PIE', 'USG_PCT', 'TS_PCT.1', 'PACE', 'POSS','CONTESTED_SHOTS', 'CONTESTED_SHOTS_2PT',
       'CONTESTED_SHOTS_3PT', 'DEFLECTIONS', 'CHARGES_DRAWN', 'SCREEN_ASSISTS', 'SCREEN_AST_PTS',
       'OFF_LOOSE_BALLS_RECOVERED', 'DEF_LOOSE_BALLS_RECOVERED', 'LOOSE_BALLS_RECOVERED',
       'PCT_LOOSE_BALLS_RECOVERED_OFF', 'PCT_LOOSE_BALLS_RECOVERED_DEF', 'OFF_BOXOUTS',
       'DEF_BOXOUTS', 'BOX_OUTS', 'BOX_OUT_PLAYER_TEAM_REBS', 'BOX_OUT_PLAYER_REBS',
       'PCT_BOX_OUTS_OFF', 'PCT_BOX_OUTS_DEF', 'PCT_BOX_OUTS_TEAM_REB', 'PCT_BOX_OUTS_REB','y']]

NameError: ignored