<a href="https://colab.research.google.com/github/jonathanluo23/NBA-allstar-all-nba-Prediction/blob/main/Capstone_All_Star_NBA_Standardization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from mlxtend.preprocessing import minmax_scaling
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats


# Mount google drive
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/

In [ ]:
pd.set_option('display.max_columns', 500)

#Import Data

In [ ]:
df_1 = pd.read_csv('/content/drive/MyDrive/Capstone/all star data /all_star_data_2012_target - all_star_data_2012.csv')
df_2 = pd.read_csv('/content/drive/MyDrive/Capstone/all star data /all_star_data_2013_target - all_star_data_2013.csv')
df_3 = pd.read_csv('/content/drive/MyDrive/Capstone/all star data /all_star_data_2014_target - all_star_data_2014.csv')
df_4 = pd.read_csv('/content/drive/MyDrive/Capstone/all star data /all_star_data_2015_target - all_star_data_2015.csv')
df_5 = pd.read_csv('/content/drive/MyDrive/Capstone/all star data /all_star_data_2016_target - all_star_data_2016.csv')
df_6 = pd.read_csv('/content/drive/MyDrive/Capstone/all star data /all_star_data_2017_target - all_star_data_2017.csv')
df_7 = pd.read_csv('/content/drive/MyDrive/Capstone/all star data /all_star_data_2018_target - all_star_data_2018.csv')
df_8 = pd.read_csv('/content/drive/MyDrive/Capstone/all star data /all_star_data_2019_target - all_star_data_2019.csv')
df_9 = pd.read_csv('/content/drive/MyDrive/Capstone/all star data /all_star_data_2020_target - all_star_data_2020.csv')
df_10 = pd.read_csv('/content/drive/MyDrive/Capstone/all star data /all_star_data_2021_target - all_star_data_2021.csv')
df_11 = pd.read_csv('/content/drive/MyDrive/Capstone/all star data /all_star_data_2022_target - all_star_data_2022.csv')

In [ ]:
df_1.insert(1,'year', 2012, True)
df_2.insert(1,'year', 2013, True)
df_3.insert(1,'year', 2014, True)
df_4.insert(1,'year', 2015, True)
df_5.insert(1,'year', 2016, True)
df_6.insert(1,'year', 2017, True)
df_7.insert(1,'year', 2018, True)
df_8.insert(1,'year', 2019, True)
df_9.insert(1,'year', 2020, True)
df_10.insert(1,'year', 2021, True)
df_11.insert(1,'year', 2022, True)

In [ ]:
df_1

,PLAYER_ID,year,PLAYER_NAME_x,W_PCT_x,OFF_RATING,DEF_RATING,NET_RATING,AST_PCT,AST_TO,TM_TOV_PCT,TS_PCT,OREB_PCT,DREB_PCT,REB_PCT,EFG_PCT,PIE,USG_PCT,TS_PCT.1,PACE,POSS,PLAYER_NAME_y,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP_y,W,L,W_PCT_y,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,TOV,STL,BLK,PF,PTS,PLUS_MINUS,y
0,201985,2012,AJ Price,0.619,97.6,92.0,5.6,0.259,2.06,11.9,0.511,0.013,0.100,0.052,0.455,0.123,0.184,0.511,93.33,531,AJ Price,AJ,1610612754,IND,25,21,13,8,0.619,12.9,1.6,4.2,0.371,0.7,2.1,0.333,0.9,0.9,1.000,0.2,1.1,1.3,1.8,0.9,0.7,0.1,1.0,4.7,1.7,0
1,201189,2012,Aaron Gray,0.294,92.4,106.7,-14.2,0.035,0.32,21.8,0.477,0.120,0.291,0.198,0.491,0.074,0.130,0.477,91.17,542,Aaron Gray,Aaron,1610612761,TOR,27,17,5,12,0.294,16.8,1.6,3.2,0.491,0.0,0.0,0.000,0.4,1.1,0.333,2.1,4.3,6.4,0.4,1.1,0.6,0.4,2.6,3.5,-4.4,0
2,1733,2012,Al Harrington,0.514,106.0,100.8,5.2,0.093,0.71,12.2,0.537,0.045,0.180,0.113,0.513,0.106,0.247,0.537,96.60,1924,Al Harrington,Al,1610612743,DEN,32,35,18,17,0.514,27.3,5.5,12.0,0.455,1.4,4.5,0.308,2.0,3.1,0.664,1.2,4.9,6.1,1.5,2.1,1.0,0.2,2.9,14.3,2.9,0
3,201143,2012,Al Horford,0.636,108.6,100.3,8.3,0.113,1.50,10.4,0.585,0.077,0.156,0.116,0.553,0.130,0.174,0.585,90.07,652,Al Horford,Al,1610612737,ATL,26,11,7,4,0.636,31.6,5.2,9.4,0.553,0.0,0.1,0.000,2.0,2.7,0.733,2.4,4.6,7.0,2.2,1.5,0.9,1.3,1.9,12.4,4.7,0
4,2744,2012,Al Jefferson,0.448,105.9,106.0,-0.1,0.108,1.63,5.5,0.510,0.073,0.224,0.148,0.481,0.156,0.276,0.510,92.42,1830,Al Jefferson,Al,1610612762,UTA,27,29,13,16,0.448,32.9,8.3,17.3,0.481,0.0,0.1,0.000,2.4,3.2,0.761,2.3,7.1,9.4,2.0,1.2,0.9,1.6,2.5,19.1,-0.7,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
443,2584,2012,Willie Green,0.588,97.0,102.8,-5.8,0.088,1.08,8.5,0.565,0.017,0.082,0.049,0.545,0.093,0.202,0.565,92.63,1124,Willie Green,Willie,1610612737,ATL,30,34,20,14,0.588,17.1,3.1,6.6,0.471,1.0,2.3,0.429,0.6,0.7,0.875,0.3,1.3,1.6,0.8,0.7,0.5,0.1,1.2,7.8,-1.8,0
444,202333,2012,Xavier Henry,0.385,96.2,97.8,-1.6,0.085,0.80,13.3,0.443,0.030,0.079,0.053,0.426,0.036,0.180,0.443,91.73,314,Xavier Henry,Xavier,1610612740,NOH,21,13,5,8,0.385,12.7,1.5,3.6,0.404,0.2,0.5,0.333,0.8,1.8,0.458,0.4,0.9,1.3,0.6,0.8,0.2,0.2,0.8,3.9,-0.5,0
445,201146,2012,Yi Jianlian,0.714,95.6,97.3,-1.8,0.031,0.29,12.3,0.452,0.079,0.138,0.110,0.432,0.062,0.211,0.452,98.39,225,Yi Jianlian,i Jianlian,1610612742,DAL,24,14,10,4,0.714,7.8,1.3,3.1,0.409,0.1,0.2,0.667,0.4,0.6,0.625,0.6,1.2,1.9,0.1,0.5,0.2,0.3,1.0,3.1,-0.3,0
446,2216,2012,Zach Randolph,0.250,96.0,100.4,-4.4,0.067,0.57,10.3,0.516,0.078,0.175,0.127,0.479,0.143,0.240,0.516,95.91,226,Zach Randolph,Zach,1610612763,MEM,30,4,1,3,0.250,28.3,5.5,11.8,0.468,0.3,0.8,0.333,3.5,5.8,0.609,2.3,5.3,7.5,1.0,1.8,1.3,0.5,2.0,14.8,-2.5,0
447,2585,2012,Zaza Pachulia,0.588,100.1,99.7,0.4,0.081,0.93,15.8,0.572,0.093,0.175,0.134,0.509,0.091,0.138,0.572,90.60,1584,Zaza Pachulia,Zaza,1610612737,ATL,28,34,20,14,0.588,24.7,2.4,4.7,0.509,0.0,0.0,0.000,1.9,2.7,0.725,2.2,4.2,6.4,1.3,1.4,0.9,0.5,2.8,6.8,0.2,0

In [ ]:
allstar_nba_df = pd.concat([df_1,df_2,df_3,df_4,df_5,df_6,df_7,df_8,df_9,df_10,df_11])

In [ ]:
allstar_nba_df.loc[allstar_nba_df['y'] == 1]

,PLAYER_ID,year,PLAYER_NAME_x,W_PCT_x,OFF_RATING,DEF_RATING,NET_RATING,AST_PCT,AST_TO,TM_TOV_PCT,TS_PCT,OREB_PCT,DREB_PCT,REB_PCT,EFG_PCT,PIE,USG_PCT,TS_PCT.1,PACE,POSS,PLAYER_NAME_y,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP_y,W,L,W_PCT_y,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,TOV,STL,BLK,PF,PTS,PLUS_MINUS,y
13,2738,2012,Andre Iguodala,0.588,100.7,94.4,6.2,0.243,2.69,10.2,0.515,0.027,0.148,0.088,0.486,0.137,0.187,0.515,90.64,2262,Andre Iguodala,Andre,1610612755,PHI,28,34,20,14,0.588,35.2,4.5,10.4,0.433,1.1,2.9,0.370,2.3,3.7,0.616,1.0,5.4,6.4,5.3,2.0,1.9,0.5,1.5,12.4,4.2,1
18,101115,2012,Andrew Bynum,0.600,100.1,97.2,2.9,0.070,0.55,13.5,0.571,0.104,0.255,0.183,0.544,0.168,0.217,0.571,92.20,2001,Andrew Bynum,Andrew,1610612747,LAL,24,30,18,12,0.600,34.6,6.5,12.0,0.544,0.0,0.1,0.000,3.2,5.1,0.627,3.4,9.3,12.8,1.3,2.4,0.5,2.0,2.0,16.3,2.2,1
37,201933,2012,Blake Griffin,0.645,109.4,101.3,8.1,0.149,1.19,10.0,0.551,0.091,0.218,0.155,0.540,0.160,0.271,0.551,90.49,2149,Blake Griffin,Blake,1610612746,LAC,23,31,20,11,0.645,36.8,8.8,16.3,0.539,0.0,0.1,0.250,3.8,7.1,0.539,3.3,8.1,11.4,3.0,2.5,0.8,0.8,3.3,21.4,5.6,1
58,2546,2012,Carmelo Anthony,0.440,100.8,101.0,-0.2,0.237,1.36,10.6,0.499,0.041,0.132,0.086,0.428,0.135,0.313,0.499,94.52,1687,Carmelo Anthony,Carmelo,1610612752,NYK,28,25,11,14,0.440,34.1,7.3,18.4,0.397,1.2,3.8,0.309,5.6,6.9,0.820,1.4,4.4,5.8,4.1,3.0,1.1,0.4,2.6,21.4,0.4,1
67,2547,2012,Chris Bosh,0.794,108.7,97.4,11.3,0.094,0.96,10.0,0.557,0.052,0.185,0.124,0.501,0.141,0.239,0.557,94.54,2350,Chris Bosh,Chris,1610612748,MIA,28,34,27,7,0.794,35.2,7.1,14.4,0.494,0.2,0.8,0.269,4.1,5.0,0.817,1.6,6.7,8.3,2.0,2.1,0.9,0.8,2.5,18.4,7.5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
367,1628374,2022,Lauri Markkanen,0.605,112.7,105.9,6.8,0.068,1.81,5.6,0.557,0.037,0.131,0.086,0.526,0.093,0.185,0.557,98.27,2358,Lauri Markkanen,Lauri,1610612739,CLE,25,38,23,15,0.605,30.2,4.9,11.3,0.436,2.0,5.9,0.342,1.7,1.9,0.863,1.1,4.2,5.3,1.5,0.8,0.8,0.6,1.8,13.6,4.7,1
489,200752,2022,Rudy Gay,0.657,114.4,107.1,7.3,0.081,1.30,8.5,0.551,0.049,0.170,0.111,0.514,0.092,0.190,0.551,100.25,1458,Rudy Gay,Rudy,1610612762,UTA,35,35,23,12,0.657,20.0,3.1,7.3,0.418,1.4,4.1,0.340,1.4,1.8,0.790,1.0,3.6,4.6,1.1,0.9,0.6,0.3,1.9,8.9,2.9,1
515,1626169,2022,Stanley Johnson,0.417,113.1,113.1,0.1,0.080,2.54,7.1,0.567,0.030,0.108,0.070,0.545,0.054,0.122,0.567,100.39,1098,Stanley Johnson,Stanley,1610612747,LAL,26,24,10,14,0.417,22.0,2.5,5.1,0.480,0.7,2.1,0.314,0.9,1.3,0.677,0.7,2.5,3.2,1.4,0.5,0.7,0.4,2.8,6.5,-0.5,1
542,1628470,2022,Torrey Craig,0.370,106.0,113.4,-7.3,0.083,1.51,9.9,0.561,0.053,0.130,0.091,0.545,0.073,0.136,0.561,99.94,2267,Torrey Craig,Torrey,1610612756,PHX,31,54,20,34,0.370,20.2,2.6,5.5,0.463,0.9,2.7,0.336,0.5,0.7,0.750,1.1,2.7,3.9,1.1,0.8,0.5,0.4,1.9,6.5,-3.4,1
587,1628380,2022,Zach Collins,0.600,103.4,103.9,-0.5,0.183,1.38,16.7,0.504,0.090,0.200,0.145,0.500,0.093,0.186,0.504,104.46,177,Zach Collins,Zach,1610612759,SAS,24,5,3,2,0.600,16.4,2.4,5.4,0.444,0.6,1.4,0.429,0.4,0.8,0.500,1.6,3.6,5.2,2.2,1.6,0.8,0.4,2.2,5.8,-0.6,1

In [ ]:
allstar_nba_df_clean = allstar_nba_df[['PLAYER_ID','TEAM_ID', 'PLAYER_NAME_x','AGE', 'W_PCT_x', 'W', 'L','MIN','OFF_RATING', 'DEF_RATING',
       'NET_RATING', 'AST_PCT', 'AST_TO', 'TM_TOV_PCT', 'TS_PCT', 'OREB_PCT',
       'DREB_PCT', 'REB_PCT', 'EFG_PCT', 'PIE', 'USG_PCT', 'TS_PCT.1', 'PACE',
       'POSS','FGM', 'FGA', 'FG_PCT',
       'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB',
       'REB', 'AST', 'TOV', 'STL', 'BLK', 'PF', 'PTS', 'PLUS_MINUS', 'y']]

In [ ]:
pd.options.display.max_columns = 500

In [ ]:
allstar_nba_df_clean

,PLAYER_ID,TEAM_ID,PLAYER_NAME_x,AGE,W_PCT_x,W,L,MIN,OFF_RATING,DEF_RATING,NET_RATING,AST_PCT,AST_TO,TM_TOV_PCT,TS_PCT,OREB_PCT,DREB_PCT,REB_PCT,EFG_PCT,PIE,USG_PCT,TS_PCT.1,PACE,POSS,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,TOV,STL,BLK,PF,PTS,PLUS_MINUS,y
0,201985,1610612754,AJ Price,25,0.619,13,8,12.9,97.6,92.0,5.6,0.259,2.06,11.9,0.511,0.013,0.100,0.052,0.455,0.123,0.184,0.511,93.33,531,1.6,4.2,0.371,0.7,2.1,0.333,0.9,0.9,1.000,0.2,1.1,1.3,1.8,0.9,0.7,0.1,1.0,4.7,1.7,0
1,201189,1610612761,Aaron Gray,27,0.294,5,12,16.8,92.4,106.7,-14.2,0.035,0.32,21.8,0.477,0.120,0.291,0.198,0.491,0.074,0.130,0.477,91.17,542,1.6,3.2,0.491,0.0,0.0,0.000,0.4,1.1,0.333,2.1,4.3,6.4,0.4,1.1,0.6,0.4,2.6,3.5,-4.4,0
2,1733,1610612743,Al Harrington,32,0.514,18,17,27.3,106.0,100.8,5.2,0.093,0.71,12.2,0.537,0.045,0.180,0.113,0.513,0.106,0.247,0.537,96.60,1924,5.5,12.0,0.455,1.4,4.5,0.308,2.0,3.1,0.664,1.2,4.9,6.1,1.5,2.1,1.0,0.2,2.9,14.3,2.9,0
3,201143,1610612737,Al Horford,26,0.636,7,4,31.6,108.6,100.3,8.3,0.113,1.50,10.4,0.585,0.077,0.156,0.116,0.553,0.130,0.174,0.585,90.07,652,5.2,9.4,0.553,0.0,0.1,0.000,2.0,2.7,0.733,2.4,4.6,7.0,2.2,1.5,0.9,1.3,1.9,12.4,4.7,0
4,2744,1610612762,Al Jefferson,27,0.448,13,16,32.9,105.9,106.0,-0.1,0.108,1.63,5.5,0.510,0.073,0.224,0.148,0.481,0.156,0.276,0.510,92.42,1830,8.3,17.3,0.481,0.0,0.1,0.000,2.4,3.2,0.761,2.3,7.1,9.4,2.0,1.2,0.9,1.6,2.5,19.1,-0.7,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
587,1628380,1610612759,Zach Collins,24,0.600,3,2,16.4,103.4,103.9,-0.5,0.183,1.38,16.7,0.504,0.090,0.200,0.145,0.500,0.093,0.186,0.504,104.46,177,2.4,5.4,0.444,0.6,1.4,0.429,0.4,0.8,0.500,1.6,3.6,5.2,2.2,1.6,0.8,0.4,2.2,5.8,-0.6,1
588,203897,1610612741,Zach LaVine,27,0.660,31,16,34.6,113.2,110.7,2.5,0.206,1.63,10.1,0.606,0.008,0.128,0.070,0.561,0.131,0.287,0.606,99.85,3386,8.7,18.1,0.482,2.9,7.2,0.399,4.2,4.9,0.869,0.3,4.6,4.9,4.5,2.7,0.6,0.4,1.7,24.6,2.1,0
589,1630192,1610612743,Zeke Nnaji,21,0.590,23,16,16.7,108.1,110.8,-2.7,0.035,0.71,8.7,0.652,0.081,0.146,0.112,0.645,0.083,0.148,0.652,98.94,1341,2.4,4.5,0.540,0.9,1.9,0.487,1.0,1.6,0.613,1.4,2.3,3.7,0.4,0.5,0.3,0.3,1.9,6.8,-1.0,0
590,1630533,1610612763,Ziaire Williams,20,0.650,26,14,21.5,111.6,110.0,1.6,0.053,1.52,7.0,0.535,0.011,0.064,0.037,0.521,0.044,0.138,0.535,101.88,1829,2.9,6.5,0.441,1.1,3.7,0.284,0.5,0.6,0.760,0.3,1.5,1.8,0.9,0.6,0.6,0.2,2.0,7.3,0.8,0
591,1629597,1610612762,Zylan Cheatham,26,0.000,0,1,5.2,18.2,125.0,-106.8,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.000,-0.167,0.250,0.000,106.50,11,0.0,3.0,0.000,0.0,2.0,0.000,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-13.0,0

| Features | Data Type | Description |
| ------------ | ---------- | ---------- |
OFF_RATING | Integer | Avg. keyword (min. shares)
DEF_RATING | Integer | Avg. keyword (avg. shares)
NET_RATING | Integer | Max. shares of referenced articles in Mashable
x5 | Integer | Avg. shares of referenced articles in Mashable
x13 | Nominal | Was article published on a Saturday?

#Data Quality Checks

##Check for nulls

In [ ]:
#Check the count of missing data entries for each column
allstar_nba_df_clean.isna().sum()

PLAYER_ID        0
TEAM_ID          0
PLAYER_NAME_x    0
AGE              0
W_PCT_x          0
W                0
L                0
MIN              0
OFF_RATING       0
DEF_RATING       0
NET_RATING       0
AST_PCT          0
AST_TO           0
TM_TOV_PCT       0
TS_PCT           0
OREB_PCT         0
DREB_PCT         0
REB_PCT          0
EFG_PCT          0
PIE              0
USG_PCT          0
TS_PCT.1         0
PACE             0
POSS             0
FGM              0
FGA              0
FG_PCT           0
FG3M             0
FG3A             0
FG3_PCT          0
FTM              0
FTA              0
FT_PCT           0
OREB             0
DREB             0
REB              0
AST              0
TOV              0
STL              0
BLK              0
PF               0
PTS              0
PLUS_MINUS       0
y                0
dtype: int64

#Continuous/Categorical-Discrete Data

#EDA

#Preprocessing